//! The single list of commands the webview is allowed to call.
//!
//! Kept out of `lib.rs` because that file is the application wiring —
//! plugins, managed state, window events — which is stable, while this list
//! grows with every feature. Together they crossed the 200-line limit; apart,
//! each file reads as one thing.

use tauri::ipc::Invoke;
use tauri::Wry;

use super::{
    account, agent_approvals_cmd, agent_chat, agent_chat_prompt, agent_config, agent_conversations,
    agent_mail_cmd, agent_roster, agent_routines_cmd, agent_skills_cmd, agents, ai, ai_memory,
    ai_service, clipboard, conversation_carry, fs, github, memory, memory_browser, perf, preview,
    probe, provider_accounts, render, report, review, screenshot, screenshot_reveal, session,
    settings, terminal, voice, workspaces,
};

pub fn handler() -> impl Fn(Invoke<Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        account::account_snapshot,
        account::account_restore,
        account::account_login_email,
        account::account_signup_email,
        account::account_oauth_start,
        account::account_oauth_cancel,
        account::account_profile_refresh,
        account::account_profile_update,
        account::account_password_forgot,
        account::account_resend_verification,
        account::account_logout,
        account::account_open_legal,
        terminal::create_terminal,
        terminal::safe_workspace_preflight,
        review::review_status,
        review::review_file_diff,
        review::review_merge,
        review::review_discard,
        review::review_list_worktrees,
        review::review_prune_worktrees,
        github::github_status,
        github::github_create_pr,
        github::github_list_branches,
        github::github_pr_state,
        github::github_open_pr,
        workspaces::workspaces_disk_usage,
        terminal::create_ssh_terminal,
        terminal::write_terminal,
        terminal::resize_terminal,
        terminal::set_terminal_visibility,
        terminal::terminal_snapshot,
        terminal::kill_terminal,
        terminal::remove_terminal,
        terminal::list_terminals,
        agents::list_agents,
        agent_roster::agent_profile_list,
        agent_roster::agent_profile_create,
        agent_roster::agent_profile_update,
        agent_roster::agent_profile_archive,
        agent_roster::agent_profile_delete,
        agent_roster::agent_place_list,
        agent_roster::agent_place_grant,
        agent_roster::agent_place_revoke,
        agent_roster::agent_engine_capabilities,
        agent_chat::agent_chat_list,
        agent_chat::agent_chat_create,
        agent_chat::agent_chat_events,
        agent_chat::agent_chat_amend,
        agent_chat::agent_chat_mount,
        agent_chat::agent_chat_delete,
        agent_chat::agent_chat_search,
        agent_chat::agent_chat_attach,
        agent_chat::agent_turn_send,
        agent_chat::agent_turn_cancel,
        agent_chat::agent_turn_running,
        agent_config::agent_memory_list,
        agent_config::agent_memory_add,
        agent_config::agent_memory_set_status,
        agent_config::agent_memory_amend,
        agent_config::agent_memory_delete,
        agent_skills_cmd::skill_list,
        agent_skills_cmd::skill_install,
        agent_skills_cmd::skill_revise,
        agent_skills_cmd::skill_set_status,
        agent_skills_cmd::skill_assign,
        agent_skills_cmd::skill_assigned,
        agent_skills_cmd::skill_history,
        agent_skills_cmd::skill_roll_back,
        agent_routines_cmd::routine_list,
        agent_routines_cmd::routine_create,
        agent_routines_cmd::routine_update,
        agent_routines_cmd::routine_set_enabled,
        agent_routines_cmd::routine_delete,
        agent_routines_cmd::routine_history,
        agent_routines_cmd::routine_zones,
        agent_approvals_cmd::approval_list,
        agent_approvals_cmd::approval_resolve,
        agent_mail_cmd::agent_mail_send,
        agent_mail_cmd::agent_mail_trail,
        agent_mail_cmd::agent_mail_allowlist,
        agent_mail_cmd::agent_mail_set_allowlist,
        agent_conversations::agent_conversation_resumable,
        agent_chat_prompt::agent_chat_prompt,
        conversation_carry::carry_agent_conversation,
        render::renderer_policy,
        provider_accounts::provider_accounts,
        provider_accounts::connect_provider_account,
        provider_accounts::add_provider_account,
        provider_accounts::remove_provider_account,
        provider_accounts::install_provider_cli,
        provider_accounts::submit_provider_account_input,
        provider_accounts::cancel_provider_account,
        provider_accounts::open_provider_sign_in_page,
        provider_accounts::disconnect_provider_account,
        fs::fs_list_dir,
        fs::fs_read_preview,
        fs::fs_home_dir,
        fs::watch_workspace,
        fs::unwatch_workspace,
        preview::preview_inspect,
        preview::preview_start,
        preview::preview_status,
        preview::preview_stop,
        preview::preview_stop_project,
        session::save_terminal_session,
        session::load_terminal_session,
        session::clear_terminal_session,
        session::confirm_close,
        session::arm_close_guard,
        session::ack_close_request,
        settings::get_settings,
        settings::save_settings,
        screenshot::capture_screen,
        screenshot::finish_screenshot_edit,
        screenshot::copy_screenshot,
        screenshot::copy_saved_screenshot,
        screenshot::save_screenshot,
        screenshot_reveal::reveal_screenshot,
        clipboard::read_clipboard_paste,
        clipboard::write_clipboard_text,
        voice::voice_status,
        voice::voice_start,
        voice::voice_stop,
        ai::ai_chat,
        ai_memory::load_memory,
        ai_memory::save_memory,
        ai_service::ai_service_status,
        ai_service::set_openai_key,
        ai_service::clear_openai_key,
        ai_service::open_openai_key_page,
        memory::memory_sources,
        memory::connect_obsidian_vault,
        memory::disconnect_obsidian_vault,
        memory::pick_memory_files,
        memory::search_memory_sources,
        memory_browser::memory_note_index,
        memory_browser::read_memory_note,
        // Spelled out rather than imported above: the crate root of the app has its
        // own `perf` and `report` modules (the sampler and the delivery
        // half), so the bare names would resolve to the wrong ones.
        perf::perf_sample,
        probe::probe_report,
        probe::probe_config,
        report::submit_report,
    ]
}
