//! The single list of commands the webview is allowed to call.
//!
//! Kept out of `lib.rs` because that file is the application wiring —
//! plugins, managed state, window events — which is stable, while this list
//! grows with every feature. Together they crossed the 200-line limit; apart,
//! each file reads as one thing.

use tauri::ipc::Invoke;
use tauri::Wry;

use super::{
    account, account_billing, account_security, agent_conversations, agents, ai, ai_memory,
    ai_service, clipboard, fs, github_publish, memory, memory_browser, perf, phone, preview,
    provider_accounts, render, report, scaffold, screenshot, screenshot_reveal, session, settings,
    shared_chats, shared_cli, speech, teammate_upload, teammates, terminal, voice,
};

pub fn handler() -> impl Fn(Invoke<Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        teammates::teammate_request,
        teammate_upload::teammate_upload,
        shared_cli::shared_cli_attach,
        shared_cli::shared_cli_write,
        shared_cli::shared_cli_resize,
        shared_cli::shared_cli_visibility,
        shared_chats::shared_chat_list,
        shared_chats::shared_chat_open_link,
        shared_chats::shared_chat_remove_project,
        shared_chats::shared_chat_create,
        shared_chats::shared_chat_request,
        phone::phone_status,
        phone::phone_configure,
        phone::phone_set_typing,
        phone::phone_set_remote,
        phone::phone_remote_disconnect_all,
        phone::phone_publish_workspace,
        phone::phone_terminal_requests,
        phone::phone_terminal_reply,
        phone::phone_invite,
        phone::phone_answer,
        phone::phone_revoke,
        phone::phone_disconnect_device,
        phone::phone_vault_choose,
        phone::phone_vault_clear,
        account::account_snapshot,
        account::account_restore,
        account::account_login_email,
        account::account_signup_email,
        account::account_oauth_start,
        account::account_oauth_cancel,
        account::account_profile_refresh,
        account::account_profile_update,
        account::account_password_forgot,
        account::account_resend_verification,
        account::account_two_factor_submit,
        account::account_two_factor_cancel,
        account::account_avatar,
        account::account_logout,
        account::account_open_legal,
        account_security::account_two_factor_status,
        account_security::account_two_factor_start,
        account_security::account_two_factor_confirm,
        account_security::account_two_factor_recovery_codes,
        account_security::account_two_factor_disable,
        account_security::account_provider_security,
        account_security::account_devices,
        account_security::account_device_revoke,
        account_security::account_devices_revoke_all,
        account_security::account_delete_with_password,
        account_security::account_delete_with_provider,
        account_security::account_delete_cancel,
        account_billing::account_credits,
        account_billing::account_topup_options,
        account_billing::account_billing_portal,
        account_billing::account_billing_topup,
        account_billing::account_billing_page,
        terminal::create_terminal,
        terminal::safe_workspace_preflight,
        terminal::safe_workspace_supported,
        terminal::set_up_git_repository,
        terminal::create_ssh_terminal,
        terminal::write_terminal,
        terminal::resize_terminal,
        terminal::set_terminal_visibility,
        terminal::terminal_snapshot,
        terminal::kill_terminal,
        terminal::remove_terminal,
        terminal::list_terminals,
        terminal::terminal_session_identities,
        agents::list_agents,
        agent_conversations::agent_conversation_resumable,
        render::renderer_policy,
        provider_accounts::provider_accounts,
        provider_accounts::connect_provider_account,
        provider_accounts::add_provider_account,
        provider_accounts::remove_provider_account,
        provider_accounts::install_provider_cli,
        provider_accounts::submit_provider_account_input,
        provider_accounts::cancel_provider_account,
        provider_accounts::open_provider_sign_in_page,
        provider_accounts::disconnect_provider_account,
        fs::fs_changes,
        fs::workspace_worktrees,
        fs::fs_change_preview,
        fs::fs_list_dir,
        fs::fs_read_preview,
        fs::fs_home_dir,
        scaffold::scaffold_preflight,
        scaffold::scaffold_run,
        scaffold::scaffold_cancel,
        github_publish::github_publish,
        fs::watch_workspace,
        fs::unwatch_workspace,
        preview::preview_inspect,
        preview::preview_start,
        preview::preview_status,
        preview::preview_stop,
        preview::preview_stop_project,
        preview::preview_open_url,
        session::save_terminal_session,
        session::load_terminal_session,
        session::clear_terminal_session,
        session::confirm_close,
        session::arm_close_guard,
        session::ack_close_request,
        settings::get_settings,
        settings::save_settings,
        screenshot::capture_screen,
        screenshot::finish_screenshot_edit,
        screenshot::copy_screenshot,
        screenshot::copy_saved_screenshot,
        screenshot::save_screenshot,
        screenshot_reveal::reveal_screenshot,
        clipboard::read_clipboard_paste,
        speech::speech_start,
        speech::speech_stop,
        speech::speech_active,
        voice::voice_status,
        voice::voice_start,
        voice::voice_stop,
        ai::ai_chat,
        ai_memory::load_memory,
        ai_memory::save_memory,
        ai_service::ai_service_status,
        ai_service::set_openai_key,
        ai_service::clear_openai_key,
        ai_service::open_openai_key_page,
        memory::memory_sources,
        memory::connect_obsidian_vault,
        memory::disconnect_obsidian_vault,
        memory::pick_memory_files,
        memory::search_memory_sources,
        memory_browser::memory_note_index,
        memory_browser::read_memory_note,
        // Spelled out rather than imported above: the crate root of the app has its
        // own `perf` and `report` modules (the sampler and the delivery
        // half), so the bare names would resolve to the wrong ones.
        perf::perf_sample,
        report::submit_report,
        report::report_channel_ready,
    ]
}
