import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  PROVIDER_LOGO_SIZE,
  PROVIDER_LOGO_SOURCES,
  PROVIDER_LOGO_SOURCE_VERSION
} from "./manifest.mjs";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "../..");
const assetDir = path.join(repoRoot, "desktop/assets/provider-logos");
const tempDir = await mkdtemp(path.join(os.tmpdir(), "vibyra-provider-logos-"));

try {
  const svgs = {};
  for (const provider of Object.keys(PROVIDER_LOGO_SOURCES)) {
    svgs[provider] = await readFile(path.join(assetDir, "sources", `${provider}.svg`), "utf8");
  }

  const inputPath = path.join(tempDir, "sources.json");
  const outputPath = path.join(tempDir, "rgba.json");
  await writeFile(inputPath, JSON.stringify(svgs));

  const electron = path.join(repoRoot, "node_modules/.bin/electron");
  const rasterizer = path.join(scriptDir, "rasterize-electron.mjs");
  const result = spawnSync(electron, ["--no-sandbox", rasterizer, inputPath, outputPath, String(PROVIDER_LOGO_SIZE)], {
    cwd: repoRoot,
    encoding: "utf8",
    env: { ...process.env, ELECTRON_DISABLE_SECURITY_WARNINGS: "true" }
  });
  if (result.status !== 0) {
    throw new Error(`Electron rasterizer failed:\n${result.stderr || result.stdout}`);
  }

  const rgbaByProvider = JSON.parse(await readFile(outputPath, "utf8"));
  const metadata = JSON.parse(await readFile(path.join(assetDir, "source-metadata.json"), "utf8"));
  const logos = {};
  for (const provider of Object.keys(PROVIDER_LOGO_SOURCES)) {
    const rgba = Buffer.from(rgbaByProvider[provider], "base64");
    assertRgba(provider, rgba);
    logos[provider] = {
      width: PROVIDER_LOGO_SIZE,
      height: PROVIDER_LOGO_SIZE,
      encoding: "rgba-rle-v1",
      rgbaRleBase64: encodeRgbaRle(rgba).toString("base64"),
      rgbaSha256: createHash("sha256").update(rgba).digest("hex")
    };
  }

  const generated = `// Generated by scripts/provider-logo-assets/generate.mjs. Do not edit.\n` +
    `export const PROVIDER_PIXEL_LOGOS = Object.freeze(${JSON.stringify(logos, null, 2)});\n\n` +
    `export const PROVIDER_PIXEL_LOGO_SOURCES = Object.freeze(${JSON.stringify(metadata, null, 2)});\n\n` +
    `export const PROVIDER_PIXEL_LOGO_BUILD = Object.freeze(${JSON.stringify({
      width: PROVIDER_LOGO_SIZE,
      height: PROVIDER_LOGO_SIZE,
      encoding: "rgba-rle-v1",
      monochromeColor: "#FFFFFF",
      sourceVersion: PROVIDER_LOGO_SOURCE_VERSION
    }, null, 2)});\n\n` +
    `export function decodeProviderPixelLogo(provider) {\n` +
    `  const logo = PROVIDER_PIXEL_LOGOS[provider];\n` +
    `  if (!logo) return null;\n` +
    `  const encoded = base64Bytes(logo.rgbaRleBase64);\n` +
    `  const rgba = new Uint8ClampedArray(logo.width * logo.height * 4);\n` +
    `  let input = 0;\n` +
    `  let output = 0;\n` +
    `  while (input < encoded.length) {\n` +
    `    const run = encoded[input] | (encoded[input + 1] << 8);\n` +
    `    for (let count = 0; count < run; count += 1) {\n` +
    `      rgba.set(encoded.subarray(input + 2, input + 6), output);\n` +
    `      output += 4;\n` +
    `    }\n` +
    `    input += 6;\n` +
    `  }\n` +
    `  if (output !== rgba.length) throw new Error("Invalid provider logo data: " + provider);\n` +
    `  return { width: logo.width, height: logo.height, rgba };\n` +
    `}\n\n` +
    `function base64Bytes(value) {\n` +
    `  if (typeof globalThis.atob === "function") {\n` +
    `    const binary = globalThis.atob(value);\n` +
    `    return Uint8Array.from(binary, (character) => character.charCodeAt(0));\n` +
    `  }\n` +
    `  return Uint8Array.from(globalThis.Buffer.from(value, "base64"));\n` +
    `}\n`;
  await writeFile(path.join(assetDir, "generated.mjs"), generated);
  console.log(`Generated ${Object.keys(logos).length} RGBA pixel logos.`);
} finally {
  await rm(tempDir, { recursive: true, force: true });
}

function assertRgba(provider, rgba) {
  const expected = PROVIDER_LOGO_SIZE * PROVIDER_LOGO_SIZE * 4;
  if (rgba.length !== expected) throw new Error(`${provider}: expected ${expected} RGBA bytes`);
  let visible = 0;
  for (let index = 3; index < rgba.length; index += 4) {
    if (rgba[index] > 0) visible += 1;
  }
  if (visible < 64) throw new Error(`${provider}: rasterized logo is effectively blank`);
}

function encodeRgbaRle(rgba) {
  const chunks = [];
  for (let offset = 0; offset < rgba.length;) {
    let run = 1;
    while (
      run < 0xffff &&
      offset + run * 4 < rgba.length &&
      rgba.subarray(offset, offset + 4).equals(rgba.subarray(offset + run * 4, offset + run * 4 + 4))
    ) run += 1;
    const chunk = Buffer.allocUnsafe(6);
    chunk.writeUInt16LE(run, 0);
    rgba.copy(chunk, 2, offset, offset + 4);
    chunks.push(chunk);
    offset += run * 4;
  }
  return Buffer.concat(chunks);
}
