import {WatchGoal} from './WatchGoal';
import {useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {findingLink,findingEvidence,goalContextText,type SignalsPage} from '../../../../../mobile/src/agents/v2/signalsModel';
import type {SignalsStore} from '../../../../../mobile/src/agents/v2/signalsStore';
export function ProjectDiscovery({page,store,disabled}:{page:SignalsPage;store:SignalsStore;disabled:boolean}) {
 const [id,setId]=useState(()=>crypto.randomUUID()),[connection,setConnection]=useState(''),[repository,setRepository]=useState(''),[goalId,setGoalId]=useState<string|null>(null);
 const watch=async()=>{await store.mutate(()=>store.api.watch({id,revision:0,agentId:store.agentId,connectionId:connection,repository,goalId,enabled:true}));if(!store.snapshot().unknown&&!store.snapshot().error){setId(crypto.randomUUID());setRepository('');}};
 return <section><p className="profile-help">Opt into one exact GitHub repository. Discovery reads pull-request status using this teammate’s existing access; findings never start work.</p>
  {page.watches.map(w=><article className="agent-work-card" key={w.id}><h4>{w.repository} · {w.status}</h4><p className="profile-help">{w.coverage}</p>{w.goalContext&&<p style={{whiteSpace:'pre-wrap'}}>{goalContextText(w.goalContext)}</p>}{w.error&&<p role="alert">Access changed or the last check failed. Review this watch before resuming.</p>}<button type="button" disabled={disabled||(!w.enabled&&!page.enabled)} onClick={()=>void store.mutate(()=>store.api.watch({...w,enabled:!w.enabled}))}>{w.enabled?'Pause project watch':'Review & resume watch'}</button><WatchGoal key={`${w.id}:${w.revision}`} watch={w} goals={page.goals} disabled={disabled||!page.enabled} save={goalId=>void store.mutate(()=>store.api.watch({...w,goalId,enabled:true}))}/></article>)}
  <label className="agent-work-field">GitHub account<select value={connection} disabled={disabled} onChange={e=>setConnection(e.target.value)}><option value="">Choose an allowed account</option>{page.connections.filter(c=>c.readGranted).map(c=><option key={c.id} value={c.id}>{c.account}</option>)}</select></label>
  {!page.connections.some(c=>c.readGranted)&&<p className="profile-help">Connect GitHub and allow this teammate to read pull requests in Access first.</p>}
  <label className="agent-work-field">GitHub repository to watch<input placeholder="owner/repository" value={repository} onChange={e=>setRepository(e.target.value)} disabled={disabled}/></label>
  <label className="agent-work-field">Compare with goal (optional)<select value={goalId??''} disabled={disabled} onChange={e=>setGoalId(e.target.value||null)}><option value="">No linked goal</option>{(page.goals??[]).map(g=><option key={g.id} value={g.id}>{g.title} · {g.status}</option>)}</select></label><button type="button" disabled={disabled||!page.enabled||!connection||!/^[-\w.]+\/[-\w.]+$/.test(repository)} onClick={()=>void watch()}>Watch this project</button>
  <p className="profile-help">The first scan records a baseline. Later changes cover the latest 30 pull requests and mergeability for up to five; coverage is partial.</p>
  {page.findings.map(f=><article className="agent-work-card" key={f.id}><h4>{f.title}</h4><p>{f.fresh?'Verified change':'Outdated finding'} · {f.source.repository} #{f.source.number}</p><p>Before: {findingEvidence(f.evidence.before)}<br/>After: {findingEvidence(f.evidence.after)}</p>{f.goalContext&&<p style={{whiteSpace:'pre-wrap'}}>{goalContextText(f.goalContext)}</p>}<p className="profile-help">Observed {new Date(f.observedAt).toLocaleString()} · source updated {new Date(f.sourceUpdatedAt).toLocaleString()}</p><div className="agent-work-actions">{findingLink(f)&&<button type="button" onClick={()=>void invoke('shared_chat_open_link',{url:findingLink(f)!})}>View source pull request</button>}<button type="button" disabled={disabled} onClick={()=>void store.mutate(()=>store.api.dismiss(f.id))}>Dismiss finding</button></div></article>)}
 </section>;
}
