import {WorkflowEditor} from './WorkflowEditor';
import type {FollowUpSource} from '../../../../../mobile/src/agents/v2/workCoreModel';
import type {WorkProposal,GoalSpec,FollowUpSpec,RoutineSpec,SkillSpec} from '../../../../../mobile/src/agents/v2/workProposalModel';
export function ProposalEditor({item,value,change,disabled,sources}:{item:WorkProposal;value:WorkProposal['spec'];change(v:WorkProposal['spec']):void;disabled:boolean;sources:FollowUpSource[]}) {
 const field=(label:string,text:string,set:(v:string)=>void,multiline=false)=><label className="agent-work-field" key={label}>{label}{multiline?<textarea aria-label={label} value={text} disabled={disabled} onChange={e=>set(e.target.value)}/>:<input aria-label={label} value={text} disabled={disabled} onChange={e=>set(e.target.value)}/>}</label>;
 if(item.kind==='workflow')return <WorkflowEditor value={value as typeof item.spec} context={item.runtime.coordination} change={change} disabled={disabled}/>;
 if(item.kind==='skill'){const s=value as SkillSpec;return <>{field('Skill name',s.name,name=>change({...s,name}))}{field('Skill instructions',s.instructions,instructions=>change({...s,instructions}),true)}<label><input type="checkbox" checked={s.assignToAgent} disabled={disabled} onChange={e=>change({...s,assignToAgent:e.target.checked})}/> Assign to this teammate</label><p className="profile-help">Saving a skill grants no tools or account access.</p></>;}
 if(item.kind==='goal'){const s=value as GoalSpec;return <>{field('Goal title',s.title,title=>change({...s,title}))}{field('Goal expiry (ISO date with timezone)',s.expiresAt,expiresAt=>change({...s,expiresAt}))}{s.milestones.map((m,index)=>{
  const patch=(v:Partial<typeof m>)=>change({...s,milestones:s.milestones.map((x,i)=>i===index?{...x,...v}:x)});
  return <section key={m.key} className="agent-work-milestone">{field(`Milestone ${index+1} title`,m.title,title=>patch({title}))}{field(`Milestone ${index+1} task`,m.prompt,prompt=>patch({prompt}),true)}{field(`Milestone ${index+1} finished means`,m.successCriteria,successCriteria=>patch({successCriteria}),true)}{s.milestones.slice(0,index).map(previous=><label key={previous.key}><input type="checkbox" checked={m.dependsOn.includes(previous.key)} disabled={disabled} onChange={()=>patch({dependsOn:m.dependsOn.includes(previous.key)?m.dependsOn.filter(k=>k!==previous.key):[...m.dependsOn,previous.key]})}/> After {previous.title}</label>)}</section>;
 })}</>;}
 if(item.kind==='followup'){const s=value as FollowUpSpec,c=s.condition;return <>{field('Follow-up title',s.title,title=>change({...s,title}))}{field('Follow-up task',s.prompt,prompt=>change({...s,prompt}),true)}{field('Follow-up expiry (ISO date with timezone)',s.expiresAt,expiresAt=>change({...s,expiresAt}))}<p>Condition: {c.kind}</p>{'at'in c&&field('Follow-up time (ISO date with timezone)',c.at,at=>change({...s,condition:{...c,at}}))}
  {'subject'in c&&<><p>Choose a verified source and exact observed subject.</p>{sources.filter(x=>x.healthy).map(source=><section key={source.triggerId}><h5>{source.title}</h5>{source.subjects.map(subject=><label key={subject.subject}><input type="radio" disabled={disabled} checked={c.triggerId===source.triggerId&&c.subject===subject.subject} onChange={()=>change({...s,condition:{...c,triggerId:source.triggerId,triggerRevision:source.triggerRevision,subject:subject.subject}})}/>{subject.label}</label>)}</section>)}</>}</>;}
 const s=value as RoutineSpec,r=s.recurrence;
 return <>{field('Routine title',s.title,title=>change({...s,title}))}{field('Routine task',s.prompt,prompt=>change({...s,prompt}),true)}{field('Routine timezone',s.timezone,timezone=>change({...s,timezone}))}<p>Repeats: {r.type}</p>{field('Routine time (HH:MM)',r.time,time=>change({...s,recurrence:{...r,time}}))}{r.type==='once'&&field('Routine date (YYYY-MM-DD)',r.date,date=>change({...s,recurrence:{...r,date}}))}{r.type==='weekly'&&[1,2,3,4,5,6,7].map(day=><label key={day}><input type="checkbox" disabled={disabled} checked={r.weekdays.includes(day)} onChange={()=>change({...s,recurrence:{...r,weekdays:r.weekdays.includes(day)?r.weekdays.filter(d=>d!==day):[...r.weekdays,day].sort()}})}/>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][day-1]}</label>)}</>;
}
