import type {WorkflowSpec} from '../../../../../mobile/src/agents/v2/coordinationModel';
import type {CoordinationReview} from '../../../../../mobile/src/agents/v2/workflowReview';
export function WorkflowEditor({value,context,change,disabled}:{value:WorkflowSpec;context?:CoordinationReview;change(v:WorkflowSpec):void;disabled:boolean}){
 const s=value,field=(label:string,text:string,set:(v:string)=>void)=><label className="agent-work-field" key={label}>{label}<textarea aria-label={label} value={text} disabled={disabled} onChange={e=>set(e.target.value)}/></label>;
 return <><p className="profile-help">Group membership and shared context remain fixed to the original reviewed message.</p>{field('Workflow title',s.title,title=>change({...s,title}))}{field('Workflow expiry (ISO date with timezone)',s.expiresAt,expiresAt=>change({...s,expiresAt}))}{s.steps.map((step,i)=>{
 const patch=(v:Partial<typeof step>)=>change({...s,steps:s.steps.map((x,j)=>i===j?{...x,...v}:x)});
 return <section key={step.key} className="agent-work-milestone">{field(`Task ${i+1} title`,step.title,title=>patch({title}))}<label className="agent-work-field">Assigned teammate<select aria-label={`Task ${i+1} teammate`} value={step.agentId} disabled={disabled} onChange={e=>patch({agentId:e.target.value})}>{context?.members.filter(m=>!s.mentions.length||s.mentions.includes(m.agentId)).map(m=><option key={m.agentId} value={m.agentId}>@{m.handle} · {m.name}</option>)}</select></label>{field(`Task ${i+1} prompt`,step.prompt,prompt=>patch({prompt}))}{field(`Task ${i+1} finished means`,step.successCriteria,successCriteria=>patch({successCriteria}))}{s.steps.slice(0,i).map(before=><label key={before.key}><input type="checkbox" disabled={disabled} checked={step.dependsOn.includes(before.key)} onChange={()=>patch({dependsOn:step.dependsOn.includes(before.key)?step.dependsOn.filter(k=>k!==before.key):[...step.dependsOn,before.key]})}/> After {before.title}</label>)}</section>;
 })}{field('Coordinator final criteria',s.finalCriteria,finalCriteria=>change({...s,finalCriteria}))}</>;
}
