<?php

return [
    'enabled' => env('CLOUD_WORKSPACES_ENABLED', false),
    'ui_enabled' => env('CLOUD_WORKSPACES_UI_ENABLED', false),
    'starts_enabled' => env('CLOUD_WORKSPACES_STARTS_ENABLED', false),
    'ai_enabled' => env('CLOUD_WORKSPACES_AI_ENABLED', false),
    'preview_enabled' => env('CLOUD_WORKSPACES_PREVIEW_ENABLED', false),
    'preview_domain' => env('CLOUD_WORKSPACES_PREVIEW_DOMAIN'),
    'pilot_users' => array_filter(explode(',', (string) env('CLOUD_WORKSPACES_PILOT_USERS', ''))),
    'tariff_version' => env('CLOUD_WORKSPACES_TARIFF_VERSION'),
    // Exact existing wallet units per hour; zero/unset refuses quotes and starts.
    'units_per_hour' => (int) env('CLOUD_WORKSPACES_UNITS_PER_HOUR', 0),
    'provider_micro_per_hour' => (int) env('CLOUD_WORKSPACES_PROVIDER_MICRO_PER_HOUR', 0),
    'region' => env('CLOUD_WORKSPACES_REGION', 'lhr'),
    'image' => env('CLOUD_WORKSPACES_IMAGE'),
    'api_origin' => env('CLOUD_WORKSPACES_API_ORIGIN', env('APP_URL')),
    'fly_token' => env('CLOUD_WORKSPACES_FLY_TOKEN'),
    'fly_org' => env('CLOUD_WORKSPACES_FLY_ORG'),
    'provider_audit_required' => env('CLOUD_WORKSPACES_PROVIDER_AUDIT_REQUIRED', true),
    'lease_private_key' => env('CLOUD_WORKSPACES_LEASE_PRIVATE_KEY'),
    'fly_url' => 'https://api.machines.dev/v1',
    'disk' => env('CLOUD_WORKSPACES_DISK', 'cloud-workspaces'),
    'volume_gib' => 20,
    'max_workspaces' => 3,
    'global_running_limit' => (int) env('CLOUD_WORKSPACES_GLOBAL_RUNNING_LIMIT', 10),
    'starts_per_account_hour' => (int) env('CLOUD_WORKSPACES_STARTS_PER_ACCOUNT_HOUR', 20),
    'starts_per_account_day' => (int) env('CLOUD_WORKSPACES_STARTS_PER_ACCOUNT_DAY', 60),
    'starts_per_global_day' => (int) env('CLOUD_WORKSPACES_STARTS_PER_GLOBAL_DAY', 200),
    'daily_micro_limit' => (int) env('CLOUD_WORKSPACES_DAILY_MICRO_LIMIT', 0),
    'account_daily_units' => (int) env('CLOUD_WORKSPACES_ACCOUNT_DAILY_UNITS', 3000000),
    'account_monthly_units' => (int) env('CLOUD_WORKSPACES_ACCOUNT_MONTHLY_UNITS', 30000000),
    'max_budget_units' => 10000000,
    'ai_turn_max_units' => (int) env('CLOUD_WORKSPACES_AI_TURN_MAX_UNITS', 50000),
    'lease_seconds' => 30,
    'runway_seconds' => 90,
    'idle_seconds' => 300,
    'max_background_seconds' => 28800,
    'boot_timeout_seconds' => 180,
    'stop_timeout_seconds' => 45,
    'stopped_days' => 7,
    'archive_days' => 30,
    'checkpoint_history' => 5,
    'max_file_bytes' => 1048576,
    'max_project_bytes' => 20971520,
    'max_files' => 2000,
    'queue_connection' => env('CLOUD_WORKSPACES_QUEUE_CONNECTION', 'database'),
];
