<?php
return [
    'events' => (bool) env('WORK_PROGRESS_EVENTS_ENABLED', false),
    'inbox' => (bool) env('NOTIFICATIONS_INBOX_ENABLED', false),
    'push' => (bool) env('NOTIFICATIONS_PUSH_ENABLED', false),
    'jev_mode' => env('JEV_DECISIONS_MODE', 'off'),
    'auto_work' => (bool) env('JEV_AUTO_WORK_ENABLED', false),
    'auto_teammate' => (bool) env('JEV_AUTO_TEAMMATE_ENABLED', false),
    'progress_mode' => env('JEV_PROGRESS_MODE', 'off'),
    'host_events' => (bool) env('HOST_NOTIFICATION_EVENTS_ENABLED', false),
    'jev_url' => 'https://openrouter.ai/api/alpha/decisions',
    'jev_model' => 'typesafe/jev-1.13',
    'jev_served_model' => 'typesafe/jev-1.13-20260917',
    'jev_key' => env('JEV_API_KEY'),
    'daily_micro_usd' => (int) env('JEV_DAILY_MICRO_USD_LIMIT', 1000000),
    'call_reserve_micro_usd' => 1000,
    'daily_calls' => (int) env('JEV_DAILY_CALL_LIMIT', 500),
    'total_micro_usd' => (int) env('JEV_TOTAL_MICRO_USD_LIMIT', 5000000),
    'minute_calls' => (int) env('JEV_MINUTE_CALL_LIMIT', 10),
    'user_daily_calls' => (int) env('JEV_USER_DAILY_CALL_LIMIT', 100),
    'user_minute_calls' => (int) env('JEV_USER_MINUTE_CALL_LIMIT', 2),
    'confidence' => 0.95,
    'expo_token' => env('EXPO_PUSH_ACCESS_TOKEN'),
    'expo_project' => env('EXPO_PROJECT_ID'),
    'environment' => env('PUSH_ENVIRONMENT', 'development'),
];
