<?php

/*
 * Reasoning controls for catalogue models that OpenRouter lists without effort levels.
 *
 * OpenRouter publishes `reasoning.supported_efforts` for some models only, and Vibyra offers an
 * effort slider only where levels are known. These entries were reviewed against each provider's
 * documentation and OpenRouter's reasoning guide on 2026-10-06. They fill gaps only: a model whose
 * OpenRouter entry already lists levels keeps OpenRouter's list.
 *
 * - efforts: OpenRouter effort values offered in the picker, cheapest first.
 * - default: what the model does when no effort is sent (null when undocumented).
 * - toggle:  thinking can only be switched on or off. "none" turns it off and any other level
 *            is sent as `reasoning.enabled`, so the provider never receives an effort it ignores.
 *
 * Models that always think at one fixed level, or cannot think, are left out: they get no slider.
 */
return [
    'models' => [
        'anthropic/claude-haiku-4.5' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'none'],
        'anthropic/claude-opus-4.1' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'none'],
        'anthropic/claude-opus-4.5' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'none'],
        'anthropic/claude-sonnet-4' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'none'],
        'anthropic/claude-sonnet-4.5' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'none'],
        'apodex/apodex-1.1-mini:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'baidu/ernie-4.5-vl-424b-a47b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'bytedance-seed/seed-1.6' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'bytedance-seed/seed-1.6-flash' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'cohere/command-a-plus' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'cohere/north-mini-code:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'deepseek/deepseek-chat-v3.1' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'deepseek/deepseek-v3.1-terminus' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'deepseek/deepseek-v3.2' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'deepseek/deepseek-v3.2-exp' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'dots-studio/dots-3-note-preview:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'google/gemini-2.5-flash' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'medium'],
        'google/gemini-2.5-flash-lite' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'none'],
        'google/gemini-2.5-pro' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'google/gemini-2.5-pro-preview' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'google/gemma-4-26b-a4b-it' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'google/gemma-4-26b-a4b-it:free' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'google/gemma-4-31b-it' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'google/gemma-4-31b-it:free' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'inclusionai/ling-3.0-flash' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'inclusionai/ling-3.0-flash-fin' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'inclusionai/ling-3.0-flash-sante:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'inclusionai/ling-3.0-flash-vl' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'inclusionai/ling-3.1-flash' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'meituan/longcat-2.0' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'high'],
        'minimax/minimax-m3' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'moonshotai/kimi-k2.5' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'moonshotai/kimi-k2.6' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'nousresearch/hermes-4-405b' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'nvidia/nemotron-3-nano-30b-a3b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'high'],
        'nvidia/nemotron-3.5-content-safety' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'nvidia/nemotron-3.5-content-safety:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'nvidia/nemotron-3.5-lightning' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'nvidia/nemotron-3.5-lightning:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'openai/gpt-5-image' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/gpt-5-image-mini' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/gpt-oss-safeguard-20b' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/o1' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/o1-pro' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/o3' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/o3-mini' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/o3-pro' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'openai/o4-mini' => ['efforts' => ['low', 'medium', 'high'], 'default' => 'medium'],
        'perceptron/perceptron-mk1' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'poolside/laguna-s-2.1' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'poolside/laguna-s-2.1:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'poolside/laguna-xs-2.1' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'poolside/laguna-xs-2.1:free' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3-14b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3-235b-a22b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3-30b-a3b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3-32b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3-8b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3-max-thinking' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-122b-a10b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-27b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-35b-a3b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-397b-a17b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-9b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-flash-02-23' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-plus-02-15' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.5-plus-20260420' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.6-27b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.6-35b-a3b' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.6-flash' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.6-max-preview' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.6-plus' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.7-flash' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'high'],
        'qwen/qwen3.7-max' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.7-plus' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'qwen/qwen3.8-flash' => ['efforts' => ['none', 'low', 'medium', 'high'], 'default' => 'high'],
        'tencent/hunyuan-a13b-instruct' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'x-ai/grok-4.20' => ['efforts' => ['none', 'high'], 'default' => 'none', 'toggle' => true],
        'xiaomi/mimo-v2.5' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'xiaomi/mimo-v2.5-pro' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'xiaomi/mimo-v2.6-flash' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'xiaomi/mimo-v2.6-pro' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'xiaomi/mimo-v2.6-pro-ultraspeed' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-4.5' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-4.5-air' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-4.5v' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-4.6' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-4.6v' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-4.7' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-4.7-flash' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-5' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-5-turbo' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-5.1' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
        'z-ai/glm-5v-turbo' => ['efforts' => ['none', 'high'], 'default' => 'high', 'toggle' => true],
    ],
];
