<?php

return [
        'slack' => [
            'name' => 'Slack',
            'tagline' => 'Workspace channels and approved posts.',
            'blurb' => 'List channels the installed bot can see, read recent messages and post one approved message as the bot.',
            'category' => 'Communication',
            'abilities' => ['List up to one hundred channels', 'Read up to twenty recent channel messages', 'Post one approved bot message'],
            'reads' => 'Channel names and recent messages available to the installed bot. Private channels require bot membership.',
            'writes' => 'Posts one message as the Vibyra bot to the exact approved channel.',
            'credential' => ['label' => 'Sign in with Slack', 'placeholder' => '',
                'help' => 'Continue to Slack to install the bot in your workspace. You will return to Vibyra when connected.',
                'url' => 'https://slack.com/signin'],
            'oauth' => [
                'authorize_url' => 'https://slack.com/oauth/v2/authorize',
                'token_url' => 'https://slack.com/api/oauth.v2.access',
                'refresh_url' => 'https://slack.com/api/oauth.v2.access',
                'scope' => 'channels:read,groups:read,channels:history,groups:history,chat:write',
                'client_id' => env('CHAT_CONNECTORS_SLACK_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_SLACK_CLIENT_SECRET'),
                'token_fields' => ['client_id', 'client_secret', 'code', 'redirect_uri'],
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'notion' => [
            'name' => 'Notion',
            'tagline' => 'Shared pages and notes.',
            'blurb' => 'Search pages you share with the Notion connection and read their top-level blocks.',
            'category' => 'Productivity',
            'abilities' => ['Search up to twenty shared pages', 'Read the first one hundred top-level blocks of a page'],
            'reads' => 'Titles and top-level blocks of pages explicitly shared with the Notion connection.',
            'writes' => null,
            'credential' => ['label' => 'Sign in with Notion', 'placeholder' => '',
                'help' => 'Continue to Notion and choose which pages to share. You will return to Vibyra when connected.',
                'url' => 'https://www.notion.so/login'],
            'oauth' => [
                'authorize_url' => 'https://api.notion.com/v1/oauth/authorize',
                'token_url' => 'https://api.notion.com/v1/oauth/token',
                'refresh_url' => 'https://api.notion.com/v1/oauth/token',
                'scope' => '', 'authorize_params' => ['owner' => 'user'],
                'client_id' => env('CHAT_CONNECTORS_NOTION_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_NOTION_CLIENT_SECRET'),
                'token_auth' => 'basic', 'token_encoding' => 'json',
                'token_fields' => ['code', 'redirect_uri', 'grant_type'],
                'refresh_fields' => ['refresh_token', 'grant_type'],
            ],
        ],

        'linear' => [
            'name' => 'Linear',
            'tagline' => 'Teams and issues.',
            'blurb' => 'Find teams and issues, read issue details and create one approved issue in a selected team.',
            'category' => 'Productivity',
            'abilities' => ['List up to fifty teams', 'Search and read issues', 'Create one approved issue'],
            'reads' => 'Team names, issue titles, descriptions, states and links available to your Linear account.',
            'writes' => 'Creates one issue in the exact approved team with the exact approved title and description.',
            'credential' => ['label' => 'Sign in with Linear', 'placeholder' => '',
                'help' => 'Continue to Linear and approve issue access. You will return to Vibyra when connected.',
                'url' => 'https://linear.app/login'],
            'oauth' => [
                'authorize_url' => 'https://linear.app/oauth/authorize',
                'token_url' => 'https://api.linear.app/oauth/token',
                'refresh_url' => 'https://api.linear.app/oauth/token',
                'scope' => 'read,issues:create',
                'client_id' => env('CHAT_CONNECTORS_LINEAR_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_LINEAR_CLIENT_SECRET'),
                'pkce' => true, 'prompt' => 'consent',
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id'],
            ],
        ],
];
