<?php

return [
        'gmail' => [
            'name' => 'Gmail',
            'tagline' => 'Email search, reading and sending.',
            'blurb' => 'Find and read messages in your Gmail account, then send a plain-text email only after you approve its exact contents.',
            'category' => 'Communication',
            'abilities' => ['Search up to ten matching emails', 'Read one email and its plain-text body', 'Send one approved plain-text email'],
            'reads' => 'Your Gmail search results, message headers and plain-text message bodies. Attachments are not read.',
            'writes' => 'Sends one email to one recipient after you approve its recipient, subject and full body.',
            'credential' => [
                'label' => 'Sign in with Google', 'placeholder' => '',
                'help' => 'Continue to Google to allow Gmail reading and sending. You will return to Vibyra when connected.',
                'url' => 'https://accounts.google.com/',
            ],
            'oauth' => [
                'authorize_url' => 'https://accounts.google.com/o/oauth2/v2/auth',
                'token_url' => 'https://oauth2.googleapis.com/token',
                'refresh_url' => 'https://oauth2.googleapis.com/token',
                'scope' => 'openid email https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.send',
                'client_id' => env('CHAT_CONNECTORS_GOOGLE_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_GOOGLE_CLIENT_SECRET'),
                'pkce' => true, 'access_type' => 'offline', 'prompt' => 'consent',
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'google_calendar' => [
            'name' => 'Google Calendar',
            'tagline' => 'Upcoming events and approved scheduling.',
            'blurb' => 'Review your next events and create an event on your primary calendar after approving its exact title and time.',
            'category' => 'Productivity',
            'abilities' => ['Read up to twenty upcoming events', 'Create one approved event without inviting attendees'],
            'reads' => 'Upcoming event titles, times, locations and links on your primary Google Calendar.',
            'writes' => 'Creates one event on your primary calendar after you approve its title, start, end and description. It does not invite attendees.',
            'credential' => [
                'label' => 'Sign in with Google', 'placeholder' => '',
                'help' => 'Continue to Google to allow Calendar event access. You will return to Vibyra when connected.',
                'url' => 'https://accounts.google.com/',
            ],
            'oauth' => [
                'authorize_url' => 'https://accounts.google.com/o/oauth2/v2/auth',
                'token_url' => 'https://oauth2.googleapis.com/token',
                'refresh_url' => 'https://oauth2.googleapis.com/token',
                'scope' => 'openid email https://www.googleapis.com/auth/calendar.events',
                'client_id' => env('CHAT_CONNECTORS_GOOGLE_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_GOOGLE_CLIENT_SECRET'),
                'pkce' => true, 'access_type' => 'offline', 'prompt' => 'consent',
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'google_drive' => [
            'name' => 'Google Drive',
            'tagline' => 'Files, Docs, Sheets and Slides.',
            'blurb' => 'Find files and read bounded text from Google Docs, Sheets, Slides and supported text files.',
            'category' => 'Productivity',
            'abilities' => ['Search up to twenty Drive files', 'Read one selected text file or Google document'],
            'reads' => 'File names, descriptions and bounded text from supported files you can access. Sheets read up to eight tabs per call and can continue with the next tabs.',
            'writes' => null,
            'credential' => [
                'label' => 'Sign in with Google', 'placeholder' => '',
                'help' => 'Continue to Google to allow read access to Drive files. You will return to Vibyra when connected.',
                'url' => 'https://accounts.google.com/',
            ],
            'oauth' => [
                'authorize_url' => 'https://accounts.google.com/o/oauth2/v2/auth',
                'token_url' => 'https://oauth2.googleapis.com/token',
                'refresh_url' => 'https://oauth2.googleapis.com/token',
                'scope' => 'openid email https://www.googleapis.com/auth/drive.readonly',
                'client_id' => env('CHAT_CONNECTORS_GOOGLE_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_GOOGLE_CLIENT_SECRET'),
                'pkce' => true, 'access_type' => 'offline', 'prompt' => 'consent',
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'outlook_mail' => [
            'name' => 'Outlook Mail',
            'tagline' => 'Microsoft email search, reading and sending.',
            'blurb' => 'Search and read your Outlook mailbox, then submit a plain-text email after approving its exact contents.',
            'category' => 'Communication',
            'abilities' => ['Search up to ten matching messages', 'Read one message', 'Send one approved plain-text email'],
            'reads' => 'Your Outlook message headers and bounded message bodies. Attachments are not read.',
            'writes' => 'Submits one email to one recipient after approval. Microsoft confirms acceptance, not delivery.',
            'credential' => ['label' => 'Sign in with Microsoft', 'placeholder' => '',
                'help' => 'Continue to Microsoft to allow mail access. You will return to Vibyra when connected.',
                'url' => 'https://login.microsoftonline.com/'],
            'oauth' => [
                'authorize_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
                'token_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
                'refresh_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
                'scope' => 'offline_access User.Read Mail.Read Mail.Send',
                'client_id' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_SECRET'),
                'pkce' => true,
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'outlook_calendar' => [
            'name' => 'Outlook Calendar',
            'tagline' => 'Upcoming events and approved scheduling.',
            'blurb' => 'Review upcoming events and create one event on your default Outlook calendar after approval.',
            'category' => 'Productivity',
            'abilities' => ['Read up to twenty upcoming events', 'Create one approved event without attendees'],
            'reads' => 'Event titles, times, locations and links on your default Outlook calendar.',
            'writes' => 'Creates one event without inviting attendees after you approve the exact title and time.',
            'credential' => ['label' => 'Sign in with Microsoft', 'placeholder' => '',
                'help' => 'Continue to Microsoft to allow calendar access. You will return to Vibyra when connected.',
                'url' => 'https://login.microsoftonline.com/'],
            'oauth' => [
                'authorize_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
                'token_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
                'refresh_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
                'scope' => 'offline_access User.Read Calendars.ReadWrite',
                'client_id' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_SECRET'),
                'pkce' => true,
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'onedrive' => [
            'name' => 'OneDrive',
            'tagline' => 'Microsoft files and bounded text.',
            'blurb' => 'Search OneDrive and read supported text files. Office documents and binary files are listed but not opened.',
            'category' => 'Productivity',
            'abilities' => ['Search up to twenty files', 'Read one text file up to 1 MB'],
            'reads' => 'File names and text from supported files in your OneDrive.',
            'writes' => null,
            'credential' => ['label' => 'Sign in with Microsoft', 'placeholder' => '',
                'help' => 'Continue to Microsoft to allow OneDrive read access. You will return to Vibyra when connected.',
                'url' => 'https://login.microsoftonline.com/'],
            'oauth' => [
                'authorize_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
                'token_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
                'refresh_url' => 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
                'scope' => 'offline_access User.Read Files.Read',
                'client_id' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_SECRET'),
                'pkce' => true,
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'teams' => [
            'name' => 'Microsoft Teams',
            'tagline' => 'Workplace chats and messages.',
            'blurb' => 'List your recent Teams chats and read bounded messages in one chat. Work or school accounts only.',
            'category' => 'Communication',
            'abilities' => ['List up to twenty chats', 'Read up to twenty messages in a chat'],
            'reads' => 'Chats and message text available to your Microsoft work or school account.',
            'writes' => null,
            'credential' => ['label' => 'Sign in with Microsoft', 'placeholder' => '',
                'help' => 'Continue with a Microsoft work or school account to allow Teams chat reading.',
                'url' => 'https://login.microsoftonline.com/'],
            'oauth' => [
                'authorize_url' => 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize',
                'token_url' => 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token',
                'refresh_url' => 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token',
                'scope' => 'offline_access User.Read Chat.Read',
                'client_id' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_SECRET'),
                'pkce' => true,
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],

        'sharepoint' => [
            'name' => 'SharePoint',
            'tagline' => 'Sites and document libraries.',
            'blurb' => 'Find sites and files, then read bounded text files in a site’s default library. Work or school accounts only.',
            'category' => 'Productivity',
            'abilities' => ['Find up to twenty sites', 'Search up to twenty files in a site', 'Read one supported text file'],
            'reads' => 'Sites and files available to your Microsoft work or school account; only supported text file content is opened.',
            'writes' => null,
            'credential' => ['label' => 'Sign in with Microsoft', 'placeholder' => '',
                'help' => 'Continue with a Microsoft work or school account to allow SharePoint reading.',
                'url' => 'https://login.microsoftonline.com/'],
            'oauth' => [
                'authorize_url' => 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize',
                'token_url' => 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token',
                'refresh_url' => 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token',
                'scope' => 'offline_access User.Read Sites.Read.All',
                'client_id' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_ID'),
                'client_secret' => env('CHAT_CONNECTORS_MICROSOFT_CLIENT_SECRET'),
                'pkce' => true,
                'refresh_fields' => ['refresh_token', 'grant_type', 'client_id', 'client_secret'],
            ],
        ],
];
