import { Platform, StyleSheet } from "react-native";

export const editPermissionStyles = StyleSheet.create({
  card: {
    borderRadius: 14,
    borderWidth: 1,
    gap: 11,
    marginTop: 10,
    overflow: "hidden",
    padding: 13,
  },
  headerText: { flex: 1, minWidth: 0 },
  kicker: { fontSize: 10.5, fontWeight: "900", letterSpacing: 0.2 },
  kickerPill: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 5,
    minHeight: 27,
    paddingHorizontal: 9,
  },
  kickerRow: { alignItems: "center", flexDirection: "row", gap: 10, justifyContent: "space-between" },
  fileCount: { fontSize: 11, fontWeight: "800" },
  title: { fontSize: 16, fontWeight: "900", lineHeight: 20 },
  subtitle: { fontSize: 12.5, fontWeight: "700", lineHeight: 18, marginTop: 4 },
  fileList: {
    gap: 7,
  },
  fileGroup: {
    borderRadius: 12,
    borderWidth: 1,
    gap: 8,
    padding: 9,
  },
  fileIcon: {
    alignItems: "center",
    borderRadius: 9,
    height: 27,
    justifyContent: "center",
    width: 27,
  },
  fileRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  filePath: { flex: 1, fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 12, fontWeight: "700", minWidth: 0 },
  inlineReview: { marginTop: 2 },
  reviewButton: { alignItems: "center", borderRadius: 999, borderWidth: 1, justifyContent: "center", minHeight: 28, paddingHorizontal: 11 },
  reviewButtonText: { fontSize: 12, fontWeight: "900" },
  actions: { flexDirection: "row", gap: 8 },
  btn: {
    alignItems: "center",
    borderRadius: 999,
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    minHeight: 37,
    overflow: "hidden",
    paddingHorizontal: 13,
  },
  btnGhost: {
    borderWidth: 1,
  },
  btnGhostText: { fontSize: 13, fontWeight: "800" },
  btnPrimary: { flex: 0.95, shadowOpacity: 0.24, shadowRadius: 10 },
  btnAlways: { flex: 1.1 },
  btnAllowText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" },
  btnPressed: { transform: [{ scale: 0.97 }] },
  btnDisabled: { opacity: 0.5 },
});
