import { Platform, StyleSheet } from "react-native";

export const editPermissionStyles = StyleSheet.create({
  card: {
    backgroundColor: "rgba(15, 17, 26, 0.92)",
    borderColor: "rgba(176, 132, 255, 0.32)",
    borderRadius: 14,
    borderWidth: 1,
    gap: 12,
    marginTop: 10,
    overflow: "hidden",
    padding: 14,
  },
  gradient: { ...StyleSheet.absoluteFillObject, opacity: 0.7 },
  headerRow: { alignItems: "center", flexDirection: "row", gap: 12 },
  iconWrap: { alignItems: "center", height: 42, justifyContent: "center", width: 42 },
  iconRing: {
    backgroundColor: "rgba(142, 60, 255, 0.4)",
    borderRadius: 999,
    height: 42,
    position: "absolute",
    width: 42,
  },
  iconCore: {
    alignItems: "center",
    borderRadius: 12,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  headerText: { flex: 1, minWidth: 0 },
  kicker: { color: "#D7C4FF", fontSize: 10, fontWeight: "900", letterSpacing: 0.7, textTransform: "uppercase" },
  title: { color: "#FFFFFF", fontSize: 14.5, fontWeight: "900", lineHeight: 19, marginTop: 3 },
  fileList: {
    backgroundColor: "rgba(7, 8, 15, 0.5)",
    borderColor: "rgba(176, 132, 255, 0.18)",
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 10,
  },
  fileRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  filePath: { color: "#E5E2F0", flex: 1, fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 12, fontWeight: "700", minWidth: 0 },
  fileAdd: { color: "#4EC07A", fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 11, fontWeight: "800" },
  fileDel: { color: "#F26A6A", fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 11, fontWeight: "800" },
  moreLabel: { color: "#A29CB8", fontSize: 11, fontWeight: "700", paddingLeft: 21 },
  totalsRow: { flexDirection: "row", gap: 8 },
  totalChip: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 999,
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  totalAdd: { color: "#4EC07A", fontSize: 11, fontWeight: "800" },
  totalDel: { color: "#F26A6A", fontSize: 11, fontWeight: "800" },
  actions: { flexDirection: "row", gap: 8 },
  btn: {
    alignItems: "center",
    borderRadius: 999,
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    minHeight: 38,
    overflow: "hidden",
    paddingHorizontal: 14,
  },
  btnDeny: {
    backgroundColor: "rgba(242, 106, 106, 0.10)",
    borderColor: "rgba(242, 106, 106, 0.35)",
    borderWidth: 1,
  },
  btnDenyText: { color: "#FFB3B3", fontSize: 13, fontWeight: "800" },
  btnAllow: {
    backgroundColor: "rgba(78, 192, 122, 0.18)",
    borderColor: "rgba(78, 192, 122, 0.45)",
    borderWidth: 1,
  },
  btnAlways: { flex: 1.1 },
  btnAllowText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" },
  btnPressed: { transform: [{ scale: 0.97 }] },
  btnDisabled: { opacity: 0.5 },
});
