import { StyleSheet } from "react-native";
import { colors } from "../../../styles/theme";

export const modalStyles = StyleSheet.create({
  actions: { flexDirection: "row", gap: 12, marginTop: 10, width: "100%" },
  addTag: { alignItems: "center", borderColor: "rgba(207,199,230,0.58)", borderRadius: 999, borderStyle: "dashed", borderWidth: 1.2, flexDirection: "row", gap: 6, minHeight: 31, paddingHorizontal: 11 },
  addTagText: { color: "#CFC7E6", fontSize: 14, fontWeight: "800" },
  categoryMenu: { alignSelf: "stretch", backgroundColor: "rgba(18,18,30,0.98)", borderColor: "rgba(255,255,255,0.12)", borderRadius: 14, borderWidth: 1, marginTop: 8, overflow: "hidden" },
  categoryOption: { alignItems: "center", borderBottomColor: "rgba(255,255,255,0.06)", borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 39, paddingHorizontal: 15 },
  categoryText: { color: "#D6D0E6", fontSize: 14, fontWeight: "800" },
  categoryTextActive: { color: colors.text },
  content: { alignItems: "center", alignSelf: "center", maxWidth: 740, paddingBottom: 12, paddingHorizontal: 18, paddingTop: 6, width: "100%" },
  error: { alignSelf: "stretch", color: "#FF9AAD", fontSize: 13, fontWeight: "800", marginTop: 14 },
  header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 20, paddingTop: 10 },
  headerButton: { alignItems: "center", height: 42, justifyContent: "center", width: 42 },
  headerTitle: { color: colors.text, fontSize: 17, fontWeight: "900" },
  formPanel: { alignItems: "center", alignSelf: "stretch" },
  iconAction: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.09)", borderColor: "rgba(255,255,255,0.12)", borderRadius: 999, borderWidth: 1, height: 33, justifyContent: "center", width: 33 },
  iconActionAi: { backgroundColor: "rgba(109,53,255,0.76)" },
  iconActions: { flexDirection: "row", gap: 8, justifyContent: "center" },
  iconAttach: { alignItems: "center", backgroundColor: "#6D35FF", borderRadius: 10, height: 35, justifyContent: "center", width: 39 },
  iconEditor: { alignItems: "center", alignSelf: "stretch", gap: 7, marginBottom: 2, marginTop: 1 },
  iconError: { color: "#FF9AAD", fontSize: 12, fontWeight: "800", textAlign: "center" },
  iconImage: { height: "100%", width: "100%" },
  iconInput: { color: colors.text, flex: 1, fontSize: 14, fontWeight: "700", paddingVertical: 0 },
  iconInputWrap: { alignItems: "center", alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.58)", borderColor: "rgba(190,183,211,0.18)", borderRadius: 13, borderWidth: 1, flexDirection: "row", gap: 8, minHeight: 39, paddingHorizontal: 12 },
  iconPreview: { alignItems: "center", backgroundColor: "rgba(139,53,255,0.18)", borderColor: "rgba(185,112,255,0.34)", borderRadius: 17, borderWidth: 1, height: 64, justifyContent: "center", overflow: "hidden", shadowColor: "#8B35FF", shadowOpacity: 0.22, shadowRadius: 16, width: 64 },
  iconRing: { alignItems: "center", backgroundColor: "rgba(139,53,255,0.18)", borderColor: "rgba(185,112,255,0.28)", borderRadius: 999, borderWidth: 1, height: 70, justifyContent: "center", marginBottom: 12, shadowColor: "#8B35FF", shadowOpacity: 0.34, shadowRadius: 28, width: 70 },
  input: { alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.64)", borderColor: "rgba(190,183,211,0.22)", borderRadius: 13, borderWidth: 1, color: colors.text, fontSize: 15, fontWeight: "600", minHeight: 42, paddingHorizontal: 14, paddingVertical: 8 },
  label: { alignSelf: "stretch", color: "#BDB6CA", fontSize: 12, fontWeight: "900", marginBottom: 5, marginTop: 9 },
  page: { backgroundColor: "#080911", flex: 1 },
  primary: { alignItems: "center", borderRadius: 14, flex: 1.28, flexDirection: "row", gap: 9, justifyContent: "center", minHeight: 49, overflow: "hidden", paddingVertical: 9, position: "relative" },
  primaryDisabled: { opacity: 0.48 },
  primaryGradient: { ...StyleSheet.absoluteFillObject, borderRadius: 15 },
  primaryText: { color: colors.text, fontSize: 17, fontWeight: "900" },
  radio: { alignItems: "center", borderColor: "#8D879C", borderRadius: 999, borderWidth: 2, height: 17, justifyContent: "center", marginTop: 6, width: 17 },
  radioActive: { borderColor: "#A855FF" },
  radioDot: { backgroundColor: "#A855FF", borderRadius: 999, height: 8, width: 8 },
  secondary: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 14, flex: 1, justifyContent: "center", minHeight: 49 },
  secondaryText: { color: "#E3DDEE", fontSize: 17, fontWeight: "900" },
  select: { alignItems: "center", alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.64)", borderColor: "rgba(190,183,211,0.22)", borderRadius: 13, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 42, paddingHorizontal: 14 },
  selectText: { color: colors.text, fontSize: 15, fontWeight: "700" },
  subtitle: { color: "#B9B2C6", fontSize: 16, fontWeight: "700", lineHeight: 22, marginBottom: 0, textAlign: "center" },
  screenshotAdd: { alignItems: "center", borderColor: "rgba(207,199,230,0.58)", borderRadius: 13, borderStyle: "dashed", borderWidth: 1.2, flexDirection: "row", gap: 6, height: 38, justifyContent: "center", paddingHorizontal: 11 },
  screenshotAddAi: { alignItems: "center", backgroundColor: "rgba(109,53,255,0.78)", borderRadius: 13, height: 38, justifyContent: "center", width: 38 },
  screenshotButton: { alignItems: "center", backgroundColor: "#6D35FF", borderRadius: 10, height: 34, justifyContent: "center", width: 38 },
  screenshotButtonAi: { alignItems: "center", backgroundColor: "rgba(109,53,255,0.78)", borderRadius: 10, height: 34, justifyContent: "center", width: 38 },
  screenshotCount: { color: "#AFA8C6", fontSize: 11, fontWeight: "900", marginTop: 6 },
  screenshotError: { alignSelf: "stretch", color: "#FF9AAD", fontSize: 12, fontWeight: "800", marginTop: 7 },
  screenshotHeader: { alignItems: "center", alignSelf: "stretch", flexDirection: "row", justifyContent: "space-between" },
  screenshotImage: { height: "100%", width: "100%" },
  screenshotInput: { color: colors.text, flex: 1, fontSize: 14, fontWeight: "700", paddingVertical: 0 },
  screenshotInputWrap: { alignItems: "center", alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.58)", borderColor: "rgba(190,183,211,0.18)", borderRadius: 13, borderWidth: 1, flexDirection: "row", gap: 9, marginTop: 6, minHeight: 39, paddingHorizontal: 12 },
  screenshotRemove: { alignItems: "center", backgroundColor: "rgba(8,6,14,0.78)", borderRadius: 999, height: 20, justifyContent: "center", position: "absolute", right: 4, top: 4, width: 20 },
  screenshotRow: { alignSelf: "stretch", flexDirection: "row", flexWrap: "wrap", gap: 8 },
  screenshotThumb: { backgroundColor: "#0B0913", borderColor: "rgba(255,255,255,0.10)", borderRadius: 13, borderWidth: 1, height: 38, overflow: "hidden", position: "relative", width: 60 },
  tagChip: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.11)", borderRadius: 999, flexDirection: "row", gap: 7, minHeight: 31, paddingHorizontal: 12 },
  tagInput: { color: colors.text, flex: 1, fontSize: 15, fontWeight: "800", minWidth: 58, paddingVertical: 0 },
  tagInputWrap: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.10)", borderColor: "rgba(255,255,255,0.14)", borderRadius: 999, borderWidth: 1, flexDirection: "row", gap: 8, minHeight: 31, paddingHorizontal: 12 },
  tagText: { color: colors.text, fontSize: 14, fontWeight: "800" },
  tagsRow: { alignSelf: "stretch", flexDirection: "row", flexWrap: "wrap", gap: 8 },
  textarea: { minHeight: 58, textAlignVertical: "top" },
  title: { color: colors.text, fontSize: 28, fontWeight: "900", letterSpacing: 0, lineHeight: 34, marginBottom: 6, textAlign: "center" },
  visibilityCard: { alignItems: "center", backgroundColor: "rgba(13,14,25,0.56)", borderColor: "rgba(190,183,211,0.14)", borderRadius: 13, borderWidth: 1, flex: 1, justifyContent: "center", minHeight: 68, paddingHorizontal: 9, paddingVertical: 8 },
  visibilityCardActive: { borderColor: "#8B35FF", borderWidth: 1.5 },
  visibilityRow: { alignSelf: "stretch", flexDirection: "row", gap: 12 },
  visibilityTitle: { color: colors.text, fontSize: 13, fontWeight: "900", marginTop: 5, textAlign: "center" }
});
