import { StyleSheet } from "react-native";
import { colors } from "../../../styles/theme";
import { createThemedStyleSheet } from "../styles/themeTransform";

export const modalStyles = createThemedStyleSheet({
  aiPromptBox: { alignItems: "flex-end", alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.58)", borderColor: "rgba(190,183,211,0.18)", borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 8, minHeight: 58, paddingHorizontal: 12, paddingVertical: 10 },
  aiPromptButton: { alignItems: "center", backgroundColor: "#6D35FF", borderRadius: 8, height: 36, justifyContent: "center", width: 40 },
  aiPromptInput: { color: colors.text, flex: 1, fontSize: 14, fontWeight: "700", maxHeight: 86, minHeight: 36, paddingVertical: 0, textAlignVertical: "top" },
  addTag: { alignItems: "center", borderColor: "rgba(207,199,230,0.42)", borderRadius: 999, borderStyle: "dashed", borderWidth: 1, flexDirection: "row", gap: 6, minHeight: 31, paddingHorizontal: 11 },
  addTagText: { color: "#CFC7E6", fontSize: 13, fontWeight: "800" },
  categoryMenu: { alignSelf: "stretch", backgroundColor: "rgba(18,18,30,0.98)", borderColor: "rgba(255,255,255,0.12)", borderRadius: 8, borderWidth: 1, marginTop: 7, overflow: "hidden" },
  categoryOption: { alignItems: "center", borderBottomColor: "rgba(255,255,255,0.06)", borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 38, paddingHorizontal: 13 },
  categoryOptionCopy: { flex: 1, gap: 2, minWidth: 0 },
  categoryText: { color: "#D6D0E6", fontSize: 14, fontWeight: "800" },
  categoryTextActive: { color: colors.text },
  categorySuggestedText: { color: "#B970FF", fontSize: 11, fontWeight: "800" },
  completionBody: { alignItems: "center", gap: 11, paddingHorizontal: 28 },
  completionIcon: { alignItems: "center", backgroundColor: "rgba(185,112,255,0.17)", borderColor: "rgba(217,203,255,0.34)", borderRadius: 999, borderWidth: 1, height: 74, justifyContent: "center", width: 74 },
  completionIconSuccess: { backgroundColor: "rgba(124,241,179,0.12)", borderColor: "rgba(124,241,179,0.32)" },
  completionIconDanger: { backgroundColor: "rgba(255,154,173,0.10)", borderColor: "rgba(255,154,173,0.30)" },
  completionIconWrap: { alignItems: "center", height: 94, justifyContent: "center", width: 94 },
  completionPulse: { backgroundColor: "rgba(185,112,255,0.22)", borderRadius: 999, height: 94, position: "absolute", width: 94 },
  completionText: { color: "#BEB7D0", fontSize: 14, fontWeight: "700", lineHeight: 20, maxWidth: 340, textAlign: "center" },
  completionTitle: { color: colors.text, fontSize: 22, fontWeight: "900", textAlign: "center" },
  completionWrap: { alignItems: "center", flex: 1, justifyContent: "center", paddingBottom: 44, paddingHorizontal: 20 },
  content: { alignItems: "stretch", alignSelf: "center", maxWidth: 520, paddingHorizontal: 18, paddingTop: 8, width: "100%" },
  doneButton: { alignItems: "center", alignSelf: "stretch", backgroundColor: "rgba(255,255,255,0.07)", borderRadius: 10, justifyContent: "center", minHeight: 48 },
  error: { alignSelf: "stretch", color: "#FF9AAD", fontSize: 12.5, fontWeight: "800", lineHeight: 17 },
  firstSection: { borderTopWidth: 0, paddingTop: 6 },
  header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingHorizontal: 14, paddingTop: 10 },
  headerButton: { alignItems: "center", height: 42, justifyContent: "center", width: 42 },
  headerTitle: { color: colors.text, fontSize: 17, fontWeight: "900" },
  iconEditor: { alignItems: "center", alignSelf: "stretch", gap: 9 },
  iconError: { color: "#FF9AAD", fontSize: 12, fontWeight: "800", textAlign: "center" },
  iconImage: { height: "100%", width: "100%" },
  iconInput: { color: colors.text, flex: 1, fontSize: 14, fontWeight: "700", paddingVertical: 0 },
  iconInputWrap: { alignItems: "center", alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.58)", borderColor: "rgba(190,183,211,0.18)", borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 8, minHeight: 39, paddingHorizontal: 12 },
  iconPreview: { alignItems: "center", backgroundColor: "rgba(139,53,255,0.14)", borderColor: "rgba(185,112,255,0.25)", borderRadius: 14, borderWidth: 1, height: 62, justifyContent: "center", overflow: "hidden", width: 62 },
  input: { alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.58)", borderColor: "rgba(190,183,211,0.16)", borderRadius: 10, borderWidth: 1, color: colors.text, fontSize: 15, fontWeight: "600", minHeight: 44, paddingHorizontal: 13, paddingVertical: 9 },
  label: { alignSelf: "stretch", color: "#BDB6CA", fontSize: 12, fontWeight: "900", marginBottom: -2, marginTop: 2 },
  moreOptionsCopy: { flex: 1, minWidth: 0 },
  moreOptionsPanel: { gap: 13, paddingTop: 12 },
  moreOptionsRow: { alignItems: "center", flexDirection: "row", gap: 12, minHeight: 48 },
  moreOptionsText: { color: "#AFA8C6", fontSize: 12.5, fontWeight: "700", lineHeight: 17, marginTop: 2 },
  moreOptionsTitle: { color: colors.text, fontSize: 15, fontWeight: "900" },
  nestedSection: { borderBottomColor: "rgba(255,255,255,0.075)", borderBottomWidth: 1, gap: 11, paddingBottom: 14 },
  nestedSectionLast: { gap: 11 },
  page: { backgroundColor: "#07070A", flex: 1 },
  primary: { alignItems: "center", borderRadius: 10, flexDirection: "row", gap: 8, justifyContent: "center", minHeight: 52, overflow: "hidden", paddingVertical: 9, position: "relative", width: "100%" },
  primaryDisabled: { opacity: 0.42 },
  primaryGradient: { ...StyleSheet.absoluteFillObject, borderRadius: 10 },
  primaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  publishBlock: { gap: 10, paddingTop: 18 },
  publishLoadingOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 20 },
  publishNotice: { alignItems: "flex-start", alignSelf: "center", backgroundColor: "rgba(17,18,28,0.96)", borderColor: "rgba(185,112,255,0.24)", borderRadius: 10, borderWidth: 1, flexDirection: "row", gap: 10, marginBottom: 9, marginTop: 3, maxWidth: 520, padding: 12, width: "92%" },
  publishNoticeCopy: { flex: 1, minWidth: 0 },
  publishNoticeIcon: { alignItems: "center", backgroundColor: "rgba(185,112,255,0.12)", borderRadius: 999, height: 28, justifyContent: "center", width: 28 },
  publishNoticeIconSuccess: { backgroundColor: "rgba(124,241,179,0.10)" },
  publishNoticeIconDanger: { backgroundColor: "rgba(255,154,173,0.10)" },
  publishNoticeText: { color: "#BEB7D0", fontSize: 12.5, fontWeight: "700", lineHeight: 17, marginTop: 2 },
  publishNoticeTitle: { color: colors.text, fontSize: 13.5, fontWeight: "900" },
  requiredText: { color: "#B970FF", fontSize: 12, fontWeight: "800" },
  screenshotAdd: { alignItems: "center", borderColor: "rgba(207,199,230,0.36)", borderRadius: 8, borderStyle: "dashed", borderWidth: 1, flexDirection: "column", gap: 5, height: 78, justifyContent: "center", paddingHorizontal: 10, width: 104 },
  screenshotError: { alignSelf: "stretch", color: "#FF9AAD", fontSize: 12, fontWeight: "800", marginTop: 7 },
  screenshotImage: { height: "100%", width: "100%" },
  screenshotRemove: { alignItems: "center", backgroundColor: "rgba(8,6,14,0.78)", borderRadius: 999, height: 22, justifyContent: "center", position: "absolute", right: 5, top: 5, width: 22 },
  screenshotRow: { alignSelf: "stretch", flexDirection: "row", flexWrap: "wrap", gap: 8 },
  screenshotThumb: { backgroundColor: "#0B0913", borderColor: "rgba(255,255,255,0.10)", borderRadius: 8, borderWidth: 1, height: 78, overflow: "hidden", position: "relative", width: 104 },
  secondaryText: { color: "#E3DDEE", fontSize: 15, fontWeight: "900" },
  select: { alignItems: "center", alignSelf: "stretch", backgroundColor: "rgba(11,12,22,0.64)", borderColor: "rgba(190,183,211,0.18)", borderRadius: 10, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 42, paddingHorizontal: 13 },
  selectText: { color: colors.text, fontSize: 15, fontWeight: "700" },
  selectValueRow: { alignItems: "center", flex: 1, flexDirection: "row", gap: 8, minWidth: 0 },
  section: { borderTopColor: "rgba(255,255,255,0.075)", borderTopWidth: 1, gap: 11, paddingVertical: 15 },
  sectionHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" },
  sectionMeta: { color: "#AFA8C6", fontSize: 12, fontWeight: "700" },
  sectionTitle: { color: colors.text, fontSize: 15, fontWeight: "800" },
  statusCopy: { flex: 1, minWidth: 0 },
  statusLine: { alignItems: "flex-start", backgroundColor: "rgba(139,53,255,0.10)", borderColor: "rgba(185,112,255,0.20)", borderRadius: 8, borderWidth: 1, flexDirection: "row", gap: 8, padding: 10 },
  statusLineSuccess: { backgroundColor: "rgba(124,241,179,0.09)", borderColor: "rgba(124,241,179,0.22)" },
  statusLineDanger: { backgroundColor: "rgba(255,154,173,0.08)", borderColor: "rgba(255,154,173,0.22)" },
  statusText: { color: "#CFC7E6", fontSize: 12, fontWeight: "700", lineHeight: 16, marginTop: 2 },
  statusTitle: { color: colors.text, fontSize: 13, fontWeight: "900" },
  suggestedPill: { backgroundColor: "rgba(185,112,255,0.14)", borderRadius: 999, color: "#D7C4FF", fontSize: 11, fontWeight: "900", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 3 },
  tagChip: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.09)", borderRadius: 999, flexDirection: "row", gap: 7, minHeight: 31, paddingHorizontal: 12 },
  tagInput: { color: colors.text, flex: 1, fontSize: 15, fontWeight: "800", minWidth: 58, paddingVertical: 0 },
  tagInputWrap: { alignItems: "center", backgroundColor: "rgba(255,255,255,0.08)", borderColor: "rgba(255,255,255,0.12)", borderRadius: 999, borderWidth: 1, flexDirection: "row", gap: 8, minHeight: 31, paddingHorizontal: 12 },
  tagText: { color: colors.text, fontSize: 13, fontWeight: "800" },
  tokenCostButton: { alignItems: "center", backgroundColor: "#6D35FF", borderRadius: 8, minHeight: 36, justifyContent: "center", minWidth: 88, paddingHorizontal: 12 },
  tokenCostButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" },
  tagsRow: { alignSelf: "stretch", flexDirection: "row", flexWrap: "wrap", gap: 8 },
  textarea: { minHeight: 84, textAlignVertical: "top" },
  titleInput: { fontSize: 17, fontWeight: "800", minHeight: 48 },
  visibilityCopy: { color: "#AFA8C6", fontSize: 12.5, fontWeight: "700", lineHeight: 17, marginTop: -5 },
  visibilitySegment: { backgroundColor: "rgba(255,255,255,0.045)", borderColor: "rgba(255,255,255,0.075)", borderRadius: 8, borderWidth: 1, flexDirection: "row", gap: 4, padding: 4 },
  visibilitySegmentOption: { alignItems: "center", borderRadius: 6, flex: 1, flexDirection: "row", gap: 5, justifyContent: "center", minHeight: 36 },
  visibilitySegmentOptionActive: { backgroundColor: "rgba(255,255,255,0.10)" },
  visibilitySegmentText: { color: "#BDB7CA", fontSize: 12, fontWeight: "900" },
  visibilitySegmentTextActive: { color: colors.text }
});
