import type {StageFourApi} from '../src/agents/v2/stageFourClient';
import type {AgentGoal,AgentFollowUp} from '../src/agents/v2/workCoreModel';
import type {WorkProposal} from '../src/agents/v2/workProposalModel';
import type {SignalsPage,WorkDigest} from '../src/agents/v2/signalsModel';
export const agentId='11111111-1111-4111-8111-111111111111';
const id=(n:number)=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`;
export function workFixture(lost=false,record:(event:string)=>void=()=>{}) {
 const runtime={executionTarget:'cloud' as const,provider:'claude',accountLabel:'Ellis · Cloud Claude',accountId:'cloud-fixture-owned',model:'claude-opus-4-6',effort:'medium'};
 const base={agentId,revision:1,reason:null,runtimeId:id(9),runtime,expiresAt:'2026-12-01T12:00:00Z',createdAt:'2026-10-08T12:00:00Z',updatedAt:'2026-10-08T12:00:00Z'};
 let goal:AgentGoal={...base,id:id(2),title:'Prepare the launch',status:'awaiting_review',progress:{delivered:1,total:1},milestones:[{key:'outline',title:'Launch outline',prompt:'Prepare a launch outline from the approved notes.',successCriteria:'An outline with owners and dates.',dependsOn:[],status:'delivered',runId:id(4),evidence:{runId:id(4),answer:'Launch outline delivered with owners and dates. No messages sent.',outputIds:[],finishedAt:base.updatedAt}}]};
 let followup:AgentFollowUp={...base,id:id(3),title:'Check the launch reply',status:'active',prompt:'Draft a polite reminder if no verified reply arrives.',condition:{kind:'absence',triggerId:id(8),triggerRevision:1,subject:'thread:launch',at:'2026-11-01T09:00:00Z'},runId:null,eventId:null,evidence:null};
 let proposal:WorkProposal={...base,id:id(5),runId:id(4),kind:'skill',title:'Clear weekly summaries',spec:{name:'Clear weekly summaries',instructions:'Use plain English. Begin with decisions, then owners and dates.',assignToAgent:true},reviewHash:'review-1',status:'draft',activation:null};
 const digest:WorkDigest={id:id(6),notificationId:id(7),date:'2026-10-08',timezone:'Europe/London',createdAt:base.createdAt,read:false,items:[{notificationId:id(10),agentId,runId:id(4),conversationId:id(11),kind:'completed',title:'Launch outline ready',createdAt:base.createdAt}]};
 let page:SignalsPage={enabled:true,goals:[{id:goal.id,title:goal.title,status:goal.status}],preferences:{revision:1,mode:'all',timezone:'Europe/London',quietStart:null,quietEnd:null,digestMinute:540},onboarding:{revision:1,interests:['code'],dismissed:false,suggestions:[{key:'review',templateKey:'code',title:'Review open pull requests',reason:'Your GitHub read access is ready.',ready:true,missing:[],firstTask:{prompt:'Review the open pull requests and summarise blockers. Do not change anything.',readOnly:true}}]},watches:[],findings:[],digests:[digest],connections:[{id:id(12),provider:'github',account:'Ellis · GitHub',readGranted:true}]};
 const copy=<T,>(x:T):T=>structuredClone(x);
 const api:StageFourApi={core:{goals:async()=>[copy(goal)],goal:async()=>copy(goal),confirmGoal:async()=>{record('confirm-goal');goal={...goal,status:'completed',revision:goal.revision+1};return copy(goal);},controlGoal:async(_,action)=>{record(action+'-goal');goal={...goal,status:action==='pause'?'paused':action==='resume'?'active':'cancelled',revision:goal.revision+1};return copy(goal);},followups:async()=>[copy(followup)],followup:async()=>copy(followup),controlFollowup:async(_,action)=>{record(action+'-followup');followup={...followup,status:action==='pause'?'paused':action==='resume'?'active':'cancelled',revision:followup.revision+1};return copy(followup);},sources:async()=>[{triggerId:id(8),triggerRevision:1,kind:'gmail',title:'Launch email replies',healthy:true,subjects:[{subject:'thread:launch',label:'Launch discussion'}]}]},
 proposals:{list:async()=>[copy(proposal)],get:async()=>{record('read-proposal');return copy(proposal);},edit:async(_,spec)=>{if(proposal.kind!=='skill'||!('instructions' in spec))throw new Error('This fixture edits skills only.');record('edit-proposal');proposal={...proposal,spec,revision:proposal.revision+1,reviewHash:'review-'+(proposal.revision+1)};if(lost){lost=false;throw new Error('Simulated save response lost.');}return copy(proposal);},accept:async shown=>{if(shown.reviewHash!==proposal.reviewHash)throw new Error('Stale review');record('accept-proposal');proposal={...proposal,status:'accepted',activation:{kind:'skill',id:id(15)}};return copy(proposal);},discard:async()=>{record('discard-proposal');proposal={...proposal,status:'discarded'};return copy(proposal);}},
 signals:{read:async()=>copy(page),preferences:async p=>{record('save-notifications');page={...page,preferences:{...p,revision:p.revision+1}};return copy(page.preferences);},onboarding:async(_,p)=>{record('save-interests');page={...page,onboarding:{...p,revision:p.revision+1}};return copy(page.onboarding);},watch:async p=>{record('save-watch:'+String(p.goalId??'none'));const watch={...p,revision:p.revision+1,status:p.enabled?'watching' as const:'paused' as const,lastCheckedAt:null,nextCheckAt:null,error:null,coverage:'Latest 30 pull requests; mergeability sampled for 5.',goalContext:p.goalId?{id:goal.id,title:goal.title,status:goal.status,milestone:{key:'outline',title:'Launch outline',successCriteria:'An outline with owners and dates.',status:'delivered'},reason:'You linked this repository to this goal. Review this change against the milestone criteria; it does not prove progress.',reviewRequired:true as const}:null};page={...page,watches:[watch]};return watch;},dismiss:async()=>{},digest:async()=>copy(digest),acknowledge:async()=>{record('acknowledge-digest');}}};
 return api;
}
