import {groupMentions,type AgentGroup,type CoordinationApi,type GroupMessage,type GroupMessageBody,type SharedGroupContext} from './coordinationModel';
export interface GroupPersistence {read():Promise<string|null>;write(value:string):Promise<void>}
interface State {ready:boolean;draft:string;shared:SharedGroupContext;pending:GroupMessageBody|null;messages:GroupMessage[];busy:boolean;error:string}
const text=(v:unknown,max:number)=>typeof v==='string'&&v.length<=max;
const context=(v:SharedGroupContext)=>v&&text(v.text,4000)&&Array.isArray(v.outputs)&&v.outputs.length<=4&&v.outputs.every(o=>text(o.id,120)&&Number.isInteger(o.revision)&&o.revision>0);
const validPending=(v:GroupMessageBody|null)=>v===null||(v&&text(v.idempotencyKey,120)&&Boolean(v.idempotencyKey)&&text(v.runtimeId,120)&&Boolean(v.runtimeId)&&Number.isInteger(v.expectedRuntimeRevision)&&v.expectedRuntimeRevision>0&&Number.isInteger(v.expectedRevision)&&v.expectedRevision>0&&text(v.prompt,4000)&&Boolean(v.prompt.trim())&&Array.isArray(v.mentions)&&v.mentions.length<=8&&v.mentions.every(id=>text(id,120))&&context(v.sharedContext));
const code=(e:unknown)=>typeof e==='object'&&e&&'status'in e?Number(e.status):Number(/^(\d{3}):/.exec(String(e instanceof Error?e.message:e))?.[1]??0);
/** Exact group request survives loss/restart; changing editable text never retargets it. */
export class GroupChatStore {
 private value:State={ready:false,draft:'',shared:{text:'',outputs:[]},pending:null,messages:[],busy:false,error:''};private listeners=new Set<()=>void>();private lock=false;private epoch=0;private writes=Promise.resolve();
 constructor(private api:CoordinationApi,readonly groupId:string,private saved:GroupPersistence,private uuid:()=>string){}
 snapshot=()=>this.value;subscribe=(f:()=>void)=>{this.listeners.add(f);return()=>{this.listeners.delete(f);};};dispose=()=>{this.epoch++;this.listeners.clear();};
 private set(p:Partial<State>){this.value={...this.value,...p};this.listeners.forEach(f=>f());}
 private persist(){const json=JSON.stringify({version:1,groupId:this.groupId,draft:this.value.draft,shared:this.value.shared,pending:this.value.pending});this.writes=this.writes.then(()=>this.saved.write(json),()=>this.saved.write(json));return this.writes;}
 initialize=async()=>{const epoch=this.epoch;try{const raw=await this.saved.read();if(epoch!==this.epoch)return;if(raw){const s=JSON.parse(raw);if(s.version!==1||s.groupId!==this.groupId||!text(s.draft,4000)||!context(s.shared)||!validPending(s.pending??null))throw new Error('The saved group draft could not be restored.');this.set({draft:s.draft,shared:s.shared,pending:s.pending??null});}this.set({ready:true});await this.refresh();}catch(e){if(epoch===this.epoch)this.set({ready:false,error:e instanceof Error?e.message:'The group draft could not be restored.'});}};
 edit=(draft:string,shared=this.value.shared)=>{if(!this.value.ready||this.lock||this.value.pending)return;this.set({draft,shared});void this.persist().catch(()=>this.set({ready:false,error:'The group draft could not be saved. Reopen before sending.'}));};
 refresh=async()=>{const epoch=this.epoch;try{const messages=await this.api.messages(this.groupId);if(messages.some(m=>m.groupId!==this.groupId))throw new Error('Messages returned a different group.');if(epoch===this.epoch)this.set({messages:[...new Map([...this.value.messages,...messages].map(m=>[m.id,m])).values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id)),error:''});}catch(e){if(epoch===this.epoch)this.set({error:e instanceof Error?e.message:'Group messages could not be loaded.'});}};
 send=async(group:AgentGroup,runtimeId:string,expectedRuntimeRevision:number)=>{if(this.lock||!this.value.ready||this.value.pending||!this.value.draft.trim())return;
  if(group.id!==this.groupId||group.deletedAt||!runtimeId){this.set({error:'Select this group and an available AI account before sending.'});return;}
  try{const pending:GroupMessageBody={expectedRevision:group.revision,runtimeId,expectedRuntimeRevision,idempotencyKey:this.uuid(),prompt:this.value.draft.trim(),mentions:groupMentions(this.value.draft,group),sharedContext:this.value.shared};this.set({pending});await this.persist();await this.retry();}catch(e){this.set({error:e instanceof Error?e.message:'The group message could not be prepared.'});}
 };
 retry=async()=>{const pending=this.value.pending;if(this.lock||!pending)return;this.lock=true;const epoch=this.epoch;this.set({busy:true,error:''});
  try{await this.persist();const {message,run}=await this.api.message(this.groupId,pending);if(message.groupId!==this.groupId||message.groupRevision!==pending.expectedRevision||message.prompt!==pending.prompt||run.id!==message.planningRunId)throw new Error('The group receipt did not match. Check the original send.');if(epoch!==this.epoch)return;this.set({pending:null,draft:'',shared:{text:'',outputs:[]},messages:[message,...this.value.messages.filter(m=>m.id!==message.id)]});await this.persist();}
  catch(e){if(epoch!==this.epoch)return;let absent=false;if(code(e)>=400&&code(e)<500){try{absent=(await this.api.messages(this.groupId,pending.idempotencyKey)).length===0;}catch{/* Keep the exact request until its status is known. */}}if(epoch!==this.epoch)return;if(absent){this.set({pending:null});await this.persist();}this.set({error:`${e instanceof Error?e.message:'The send is unconfirmed.'}${absent?' Your draft is saved.':' Check the original send before starting another.'}`});}
  finally{if(epoch===this.epoch){this.lock=false;this.set({busy:false});}}
 };
}
