import {useState} from 'react';
import type {AgentGroup} from '../../../../../mobile/src/agents/v2/coordinationModel';
import type {StageFiveApi} from '../../../../../mobile/src/agents/v2/stageFiveClient';
import type {StageTwoApi} from '../../../../../mobile/src/agents/v2/stageTwoModel';
import {useGroupResources,groupRuntimeLabel,type GroupRuntime} from '../../../../../mobile/src/agents/v2/groupResources';
import type {GroupChatStore} from '../../../../../mobile/src/agents/v2/groupChatStore';
export function GroupComposer({api,outputs,group,store,state,disabled}:{api:StageFiveApi;outputs?:StageTwoApi;group:AgentGroup;store:GroupChatStore;state:ReturnType<GroupChatStore['snapshot']>;disabled:boolean}){
 const resources=useGroupResources(api,outputs,group),[runtimeId,setRuntimeId]=useState(''),[review,setReview]=useState<{group:AgentGroup;runtime:GroupRuntime}|null>(null),runtime=resources.runtimes.find(r=>r.id===runtimeId),locked=disabled||state.busy||Boolean(state.pending)||!state.ready;
 if(review&&!state.pending&&state.draft.trim())return <section className="agent-work-card"><h3>Review group message</h3><p>{groupRuntimeLabel(review.runtime)} · group version {review.group.revision}</p><p style={{whiteSpace:'pre-wrap'}}>{state.draft}</p><p>Shared context: {state.shared.text||'No extra text'}</p>{state.shared.outputs.map(o=><p key={o.id}>{resources.files.find(f=>f.id===o.id&&f.revision===o.revision)?.title??o.id} · version {o.revision}</p>)}<p>Send starts one coordinator planning task. Worker tasks start only after you review and approve the proposed workflow.</p><div className="agent-work-actions"><button type="button" className="primary" disabled={locked} onClick={()=>void store.send(review.group,review.runtime.id,review.runtime.revision)}>Send group planning task</button><button type="button" onClick={()=>setReview(null)}>Edit group message</button></div></section>;
 return <section className="agent-work-card">{state.error&&<p role="alert">{state.error}</p>}{resources.error&&<p role="alert">{resources.error}</p>}{state.pending?<><p>Checking the original group message. Its members, context and account remain fixed.</p><button type="button" disabled={state.busy} onClick={()=>void store.retry()}>Check original group send</button></>:<><label className="agent-work-field">Message this group<textarea aria-label="Message this group" value={state.draft} disabled={locked} maxLength={4000} onChange={e=>{setReview(null);store.edit(e.target.value);}}/></label><div className="agent-work-actions">{group.members.map(m=><button type="button" key={m.agentId} disabled={locked} onClick={()=>{setReview(null);store.edit(`${state.draft}${state.draft?' ':''}@${m.handle} `);}}>Mention @{m.handle}</button>)}</div><label className="agent-work-field">Shared context (optional)<textarea aria-label="Shared context (optional)" maxLength={4000} value={state.shared.text} disabled={locked} onChange={e=>{setReview(null);store.edit(state.draft,{...state.shared,text:e.target.value});}}/></label><p className="profile-help">Choose exact saved output versions to share. No private history or memory is included.</p>{resources.files.map(file=>{const chosen=state.shared.outputs.some(x=>x.id===file.id&&x.revision===file.revision);return <label key={`${file.id}:${file.revision}`}><input type="checkbox" disabled={locked||(!chosen&&state.shared.outputs.length>=4)} checked={chosen} onChange={()=>{setReview(null);store.edit(state.draft,{...state.shared,outputs:chosen?state.shared.outputs.filter(x=>x.id!==file.id):[...state.shared.outputs,{id:file.id,revision:file.revision}]});}}/>{file.title} · {file.kind} · version {file.revision}</label>;})}<label className="agent-work-field">Account for this workflow<select aria-label="Account for this workflow" value={runtimeId} disabled={locked} onChange={e=>{setRuntimeId(e.target.value);setReview(null);}}><option value="">Choose an account</option>{resources.runtimes.map(r=><option key={r.id} value={r.id} disabled={r.capabilities.controlledTools!==true||r.capabilities.parallelJobsV1!==true}>{groupRuntimeLabel(r)}{r.capabilities.parallelJobsV1!==true?' · update required':''}</option>)}</select></label><button type="button" onClick={resources.refresh}>Refresh accounts & saved outputs</button><button type="button" className="primary" disabled={locked||!state.draft.trim()||!runtime} onClick={()=>runtime&&setReview({group:{...group,members:group.members.map(m=>({...m}))},runtime:{...runtime,capabilities:{...runtime.capabilities}}})}>Review group message</button></>}</section>;
}
