import {useState} from 'react';
import {useGroupEditor} from '../../../../../mobile/src/agents/v2/useGroupEditor';
import type {AgentGroup,CoordinationApi} from '../../../../../mobile/src/agents/v2/coordinationModel';
import type {Teammate} from '../types';
export function GroupEditor({api,id,initial,teammates,disabled,onSaved,onClose}:{api:CoordinationApi;id:string;initial?:AgentGroup;teammates:Teammate[];disabled:boolean;onSaved(g:AgentGroup):void;onClose():void}){
 const [archive,setArchive]=useState(false);
 const s=useGroupEditor(api,id,initial,onSaved),locked=disabled||s.busy||s.unknown;
 return <section className="agent-work-card"><h3>Group members</h3>{s.error&&<p role="alert">{s.error}</p>}<label className="agent-work-field">Group name<input aria-label="Group name" value={s.body.name} disabled={locked} maxLength={80} onChange={e=>s.setBody({...s.body,name:e.target.value})}/></label><p>Choose two to eight teammates. Each keeps its own access; sharing a group grants no new permissions.</p>{teammates.filter(t=>!t.archived).map(t=><label key={t.id}><input type="checkbox" disabled={locked} checked={s.body.members.some(m=>m.agentId===t.id)} onChange={()=>s.toggle(t.id,t.name)}/>{t.name}</label>)}{s.body.members.map(m=><div key={m.agentId}><label className="agent-work-field">Handle for {teammates.find(t=>t.id===m.agentId)?.name??m.agentId}<input aria-label={`Handle for ${teammates.find(t=>t.id===m.agentId)?.name??m.agentId}`} value={m.handle} disabled={locked} maxLength={32} onChange={e=>s.setBody({...s.body,members:s.body.members.map(x=>x.agentId===m.agentId?{...x,handle:e.target.value}:x)})}/></label><label><input type="radio" name="coordinator" disabled={locked} checked={s.body.coordinatorId===m.agentId} onChange={()=>s.setBody({...s.body,coordinatorId:m.agentId})}/>Coordinator · @{m.handle}</label></div>)}<div className="agent-work-actions"><button type="button" className="primary" disabled={locked} onClick={()=>void s.save()}>Save group</button>{s.unknown&&<button type="button" disabled={s.busy} onClick={()=>void s.refresh()}>Refresh group after save</button>}{initial&&!initial.deletedAt&&<><button type="button" disabled={locked} onClick={()=>archive?void s.archive():setArchive(true)}>{archive?'Confirm archive group':'Archive group'}</button>{archive&&<p>New group messages stop. Saved history stays available.</p>}</>}<button type="button" disabled={s.busy||s.unknown} onClick={onClose}>Close group editor</button></div></section>;
}
