import { createRoot } from "react-dom/client";

import "@fontsource-variable/inter";
import "@fontsource-variable/jetbrains-mono";
import "@xterm/xterm/css/xterm.css";

import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/base-controls.css";
import "./styles/base-badges.css";
import "./styles/base-scrollbars.css";
import "./styles/base-motion.css";
import "./styles/base-performance.css";
import "./styles/base-activity-dots.css";
import "./styles/base-tooltips.css";
import "./styles/controls.css";
import "./styles/nav-segmented.css";
import "./styles/chrome.css";
import "./styles/chrome-nav.css";
import "./styles/chrome-resize.css";
import "./styles/chrome-account.css";
import "./styles/notifications-bell.css";
import "./styles/auth.css";
import "./styles/auth-card.css";
import "./styles/auth-backdrop.css";
import "./styles/auth-choices.css";
import "./styles/auth-reveal.css";
import "./styles/auth-status.css";
import "./styles/auth-overrides.css";
import "./styles/auth-email.css";
import "./styles/auth-email-form.css";
import "./styles/first-welcome.css";
import "./styles/first-welcome-motion.css";
import "./styles/strip.css";
import "./styles/home.css";
import "./styles/home-launch.css";
import "./styles/home-cards.css";
import "./styles/home-empty.css";
import "./styles/home-recents.css";
import "./styles/rail.css";
import "./styles/rail-files.css";
import "./styles/rail-footer.css";
import "./styles/rail-sessions.css";
import "./styles/launch-settings.css";
import "./styles/launch-controls.css";
import "./styles/launch-model-picker.css";
import "./styles/launch-approval.css";
import "./styles/workspace.css";
import "./styles/workspace-pane.css";
import "./styles/workspace-pane-states.css";
import "./styles/workspace-empty.css";
import "./styles/workspace-voice-hud.css";
import "./styles/workspace-shot-tray.css";
import "./styles/notifications-pinned.css";
import "./styles/notifications-toast.css";
import "./styles/notifications-toast-content.css";
import "./styles/notifications-toast-prompt.css";
import "./styles/notifications-toast-motion.css";
import "./styles/notifications-toast-progress.css";
import "./styles/notifications-center.css";
import "./styles/notifications-center-empty.css";
import "./styles/notifications-center-row.css";
import "./styles/preview.css";
import "./styles/preview-picker.css";
import "./styles/preview-device.css";
import "./styles/preview-overlay.css";
import "./styles/chat-thread.css";
import "./styles/chat-input.css";
import "./styles/memory-notes.css";
import "./styles/agent-mark.css";
import "./styles/agent-picker.css";
import "./styles/agent-picker-models.css";
import "./styles/dock-shell.css";
import "./styles/dock-panels.css";
import "./styles/dock-review.css";
import "./styles/dock-fleet.css";
import "./styles/dock-fleet-row.css";
import "./styles/dock-fleet-radar.css";
import "./styles/review-diff.css";
import "./styles/review-diff-rows.css";
import "./styles/review-actions.css";
import "./styles/review-changeset.css";
import "./styles/review-conflict.css";
import "./styles/companion-chat.css";
import "./styles/companion-chat-composer.css";
import "./styles/companion-memory.css";
import "./styles/companion-memory-import.css";
import "./styles/companion-memory-workbench.css";
import "./styles/companion-memory-document.css";
import "./styles/companion-files.css";
import "./styles/palette.css";
import "./styles/palette-rows.css";
import "./styles/modals.css";
import "./styles/settings-modal.css";
import "./styles/settings-pane.css";
import "./styles/settings-rows.css";
import "./styles/settings-agents.css";
import "./styles/settings-shortcuts.css";
import "./styles/settings-theme-cards.css";
import "./styles/settings-modal-narrow.css";
import "./styles/kbd.css";
import "./styles/terminal-suspended.css";
import "./styles/settings-ai-key.css";
import "./styles/settings-ai-uses.css";
import "./styles/settings-ai-usage.css";
import "./styles/settings-ai-guards.css";
import "./styles/settings-integrations.css";
import "./styles/settings-account-connect.css";
import "./styles/settings-account-switch.css";
import "./styles/settings-integration-accounts.css";
import "./styles/settings-terminal-integrations.css";
import "./styles/settings-notifications.css";
import "./styles/settings-workspaces.css";
import "./styles/report.css";
import "./styles/report-choices.css";
import "./styles/report-fields.css";
import "./styles/report-attachments.css";
import "./styles/report-context.css";
import "./styles/report-footer.css";
import "./styles/report-sent.css";
import "./styles/report-entry.css";
import "./styles/report-files.css";
import "./styles/screenshot-editor.css";
import "./styles/screenshot-controls.css";
import "./styles/screenshot-tray.css";
import "./styles/settings-graphics.css";
import "./styles/settings-performance.css";
import "./styles/settings-updates.css";
import "./styles/settings-hotkeys.css";
import "./styles/settings-profile.css";

import App from "./App";
import { installAppDropGuard } from "./lib/terminalDrop";
import { initTerminalFont } from "./lib/terminalFont";
import { initRendererPolicy } from "./lib/xtermRenderer";

// Prewarm both asynchronous resources. TerminalView and attachRenderer also
// await these cached promises, so a fast restored workspace cannot outrun them.
void initTerminalFont();
void initRendererPolicy();
installAppDropGuard();

const root = createRoot(document.getElementById("root")!);
if (import.meta.env.VITE_LATENCY_PROBE === "1") {
  // Diagnostics build only: measures keystroke-to-paint latency on the real
  // renderer. Never true in a normal build, so this import stays out of the
  // production bundle and the app below is untouched.
  void import("./probe/ProbeScreen").then(({ ProbeScreen }) => {
    root.render(<ProbeScreen />);
  });
} else {
  root.render(<App />);
}
