import { StyleSheet } from 'react-native';

const RADIUS = 28;
export const composerStyles = StyleSheet.create({
  wrap: { paddingHorizontal: 12, paddingTop: 6 },
  box: {
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
    borderRadius: RADIUS,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 10,
  },
  shine: {
    position: 'absolute',
    top: 0,
    left: RADIUS,
    right: RADIUS,
    height: StyleSheet.hairlineWidth * 2,
  },
  glow: {
    position: 'absolute',
    top: -1,
    left: -1,
    right: -1,
    bottom: -1,
    borderRadius: RADIUS + 1,
    borderWidth: 1,
    shadowOpacity: 0.9,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
  },
  input: {
    fontSize: 17,
    lineHeight: 24,
    paddingHorizontal: 8,
    paddingTop: 6,
    paddingBottom: 4,
    minHeight: 62,
    maxHeight: 150,
    outlineWidth: 0,
  },
  toolbar: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6 },
  round: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 34,
    borderRadius: 17,
    flexShrink: 1,
    minWidth: 0,
  },
  model: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 34,
    paddingLeft: 6,
    paddingRight: 6,
    flexShrink: 1,
    minWidth: 0,
  },
  divider: { width: StyleSheet.hairlineWidth, height: 16 },
  modelName: { fontSize: 13, fontWeight: '600', letterSpacing: -0.1, flexShrink: 1 },
  autoMark: {
    width: 20,
    height: 20,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    right: -4,
    bottom: -4,
    width: 13,
    height: 13,
    borderRadius: 6.5,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  space: { flex: 1 },
  send: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  computerSend: { width: 44, height: 44, borderRadius: 22 },
  estimate: { minHeight: 26, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  caption: { fontSize: 12, lineHeight: 16, textAlign: 'center' },
});
