import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const generated = resolve(root, 'src/generated');
await mkdir(generated, { recursive: true });
const wasm = await readFile(resolve(root, '../host/generated/noise/vibyra_transport_bg.wasm')).catch(() => {
  throw new Error('Build the maintained Noise transport first: run ../host/scripts/build-wasm.sh');
});
async function bundle(path, define = {}) {
  const result = await build({ entryPoints: [resolve(root, path)], bundle: true, write: false,
    minify: true, format: 'iife', platform: 'browser', target: 'safari16',
    define: { 'import.meta.url': JSON.stringify('about:blank'), ...define } });
  return result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
}
const runtime = await bundle('src/transport/runtime.ts', { NOISE_WASM_BASE64: JSON.stringify(wasm.toString('base64')) });
const terminal = await bundle('src/terminal/runtime.ts');
const css = await readFile(resolve(root, 'node_modules/@xterm/xterm/css/xterm.css'), 'utf8');
// Three things this template gets asked about:
//
// - No `maximum-scale`. It disabled pinch-to-zoom, and the terminal's own type
//   is already clamped to its 10px floor on any iPhone under ~399pt, so there
//   was no way left to make small output bigger.
// - The ground follows `prefers-color-scheme` on first paint. A hardcoded dark
//   value flashed a black WebView on a light phone until the first theme
//   message arrived, and again after every content-process reload.
// - xterm sets `user-select:none`, and its accessibility layer sits above the
//   rows, so a long-press grabbed a transparent element and no output could be
//   copied. A view-only phone needs native selection more than xterm's own.
// - The terminal fills its box and never scrolls sideways. An earlier build
//   drew the computer's full grid on a pannable, scaled stage; that is iSH's
//   behaviour, and reading should not need horizontal motion. Pinching now
//   changes the type size, and the column count follows from it.
// - The padding lives on `body`, never on the element FitAddon measures, or it
//   proposes more rows than fit and slices the newest line.
const html = (script, terminalView) => `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'unsafe-inline'; connect-src ${terminalView ? "'none'" : 'ws: wss:'};"><style>html,body{height:100%;width:100%;margin:0;overflow:hidden;background:#FBFBFC}@media (prefers-color-scheme:dark){html,body{background:#101115}}body{box-sizing:border-box;padding:8px 12px;-webkit-text-size-adjust:100%}#terminal{height:100%;touch-action:pan-y pinch-zoom}${terminalView ? css : ''}${terminalView ? '.xterm .xterm-screen,.xterm .xterm-rows{-webkit-user-select:text;user-select:text}' : ''}</style></head><body>${terminalView ? '<div id="terminal"></div>' : ''}<script>${script}</script></body></html>`;
await writeFile(resolve(generated, 'runtime.ts'), `// Generated by npm run assets.\nexport const runtimeHtml = ${JSON.stringify(html(runtime, false))};\n`);
await writeFile(resolve(generated, 'terminal.ts'), `// Generated by npm run assets.\nexport const terminalHtml = ${JSON.stringify(html(terminal, true))};\n`);
console.log('Bundled encrypted transport and isolated terminal. No remote scripts.');
