import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const generated = resolve(root, 'src/generated');
await mkdir(generated, { recursive: true });
const wasm = await readFile(resolve(root, '../host/generated/noise/vibyra_transport_bg.wasm')).catch(() => {
  throw new Error('Build the maintained Noise transport first: run ../host/scripts/build-wasm.sh');
});
async function bundle(path, define = {}) {
  const result = await build({ entryPoints: [resolve(root, path)], bundle: true, write: false,
    minify: true, format: 'iife', platform: 'browser', target: 'safari16',
    define: { 'import.meta.url': JSON.stringify('about:blank'), ...define } });
  return result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
}
const runtime = await bundle('src/transport/runtime.ts', { NOISE_WASM_BASE64: JSON.stringify(wasm.toString('base64')) });
const terminal = await bundle('src/terminal/runtime.ts');
const css = await readFile(resolve(root, 'node_modules/@xterm/xterm/css/xterm.css'), 'utf8');
const html = (script, terminalView) => `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'unsafe-inline'; connect-src ${terminalView ? "'none'" : 'ws: wss:'};"><style>html,body{height:100%;width:100%;margin:0;overflow:hidden;background:#101115}#terminal{height:100%;box-sizing:border-box;padding:12px 14px}${terminalView ? css : ''}</style></head><body>${terminalView ? '<div id="terminal"></div>' : ''}<script>${script}</script></body></html>`;
await writeFile(resolve(generated, 'runtime.ts'), `// Generated by npm run assets.\nexport const runtimeHtml = ${JSON.stringify(html(runtime, false))};\n`);
await writeFile(resolve(generated, 'terminal.ts'), `// Generated by npm run assets.\nexport const terminalHtml = ${JSON.stringify(html(terminal, true))};\n`);
console.log('Bundled encrypted transport and isolated terminal. No remote scripts.');
