import {Text,TextInput,View} from 'react-native';
import {Button,Hint} from '../../ui/primitives';
import {useTheme} from '../../theme';
import type {FollowUpSource} from '../v2/workCoreModel';
import type {WorkProposal,GoalSpec,FollowUpSpec,RoutineSpec,SkillSpec} from '../v2/workProposalModel';
export function ProposalEditor({item,value,change,disabled,sources}:{item:WorkProposal;value:WorkProposal['spec'];change(v:WorkProposal['spec']):void;disabled:boolean;sources:FollowUpSource[]}) {
 const {colors}=useTheme();
 const field=(label:string,text:string,set:(v:string)=>void,multiline=false)=><View style={{gap:5}} key={label}><Text style={{color:colors.text}}>{label}</Text><TextInput accessibilityLabel={label} value={text} editable={!disabled} multiline={multiline} onChangeText={set} style={{color:colors.text,borderColor:colors.border,borderWidth:1,borderRadius:8,padding:10,minHeight:multiline?80:42}}/></View>;
 if(item.kind==='skill'){const s=value as SkillSpec;return <View style={{gap:10}}>{field('Skill name',s.name,name=>change({...s,name}))}{field('Skill instructions',s.instructions,instructions=>change({...s,instructions}),true)}<Button secondary disabled={disabled} title={s.assignToAgent?'Assigned to this teammate':'Keep skill unassigned'} onPress={()=>change({...s,assignToAgent:!s.assignToAgent})}/><Hint>Saving a skill grants no tools or account access.</Hint></View>;}
 if(item.kind==='goal'){const s=value as GoalSpec;return <View style={{gap:10}}>{field('Goal title',s.title,title=>change({...s,title}))}{field('Goal expiry (ISO date with timezone)',s.expiresAt,expiresAt=>change({...s,expiresAt}))}{s.milestones.map((m,index)=>{
  const patch=(v:Partial<typeof m>)=>change({...s,milestones:s.milestones.map((x,i)=>i===index?{...x,...v}:x)});
  return <View key={m.key} style={{gap:8}}>{field(`Milestone ${index+1} title`,m.title,title=>patch({title}))}{field(`Milestone ${index+1} task`,m.prompt,prompt=>patch({prompt}),true)}{field(`Milestone ${index+1} finished means`,m.successCriteria,successCriteria=>patch({successCriteria}),true)}{s.milestones.slice(0,index).map(previous=><Button key={previous.key} secondary disabled={disabled} title={`${m.dependsOn.includes(previous.key)?'✓ ':''}After ${previous.title}`} onPress={()=>patch({dependsOn:m.dependsOn.includes(previous.key)?m.dependsOn.filter(k=>k!==previous.key):[...m.dependsOn,previous.key]})}/>)}</View>;
 })}</View>;}
 if(item.kind==='followup'){const s=value as FollowUpSpec,c=s.condition;return <View style={{gap:10}}>{field('Follow-up title',s.title,title=>change({...s,title}))}{field('Follow-up task',s.prompt,prompt=>change({...s,prompt}),true)}{field('Follow-up expiry (ISO date with timezone)',s.expiresAt,expiresAt=>change({...s,expiresAt}))}
  <Hint>Condition: {c.kind}</Hint>{'at'in c&&field('Follow-up time (ISO date with timezone)',c.at,at=>change({...s,condition:{...c,at}}))}
  {'subject'in c&&<><Hint>Choose a verified source and exact observed subject.</Hint>{sources.filter(x=>x.healthy).map(source=><View key={source.triggerId}><Hint>{source.title}</Hint>{source.subjects.map(subject=><Button key={subject.subject} secondary disabled={disabled} title={`${c.triggerId===source.triggerId&&c.subject===subject.subject?'✓ ':''}${subject.label}`} onPress={()=>change({...s,condition:{...c,triggerId:source.triggerId,triggerRevision:source.triggerRevision,subject:subject.subject}})}/>)}</View>)}</>}
 </View>;}
 const s=value as RoutineSpec,r=s.recurrence;
 return <View style={{gap:10}}>{field('Routine title',s.title,title=>change({...s,title}))}{field('Routine task',s.prompt,prompt=>change({...s,prompt}),true)}{field('Routine timezone',s.timezone,timezone=>change({...s,timezone}))}<Hint>Repeats: {r.type}</Hint>{field('Routine time (HH:MM)',r.time,time=>change({...s,recurrence:{...r,time}}))}{r.type==='once'&&field('Routine date (YYYY-MM-DD)',r.date,date=>change({...s,recurrence:{...r,date}}))}{r.type==='weekly'&&[1,2,3,4,5,6,7].map(day=><Button key={day} secondary disabled={disabled} title={`${r.weekdays.includes(day)?'✓ ':''}${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][day-1]}`} onPress={()=>change({...s,recurrence:{...r,weekdays:r.weekdays.includes(day)?r.weekdays.filter(d=>d!==day):[...r.weekdays,day].sort()}})}/>)}</View>;
}
