//! Account registration proves possession without exposing the Host's Noise
//! private key. Sodium-compatible sealed boxes use the same X25519 identity;
//! the API owns account/action/expiry binding and single-use consumption.
use crate::{state::Shared, EmbeddedHost};
use std::sync::Arc;

#[derive(Clone)]
pub struct RegistrationProof(pub(crate) Arc<Shared>);

impl EmbeddedHost {
    pub fn registration_proof(&self) -> RegistrationProof {
        RegistrationProof(self.shared.clone())
    }
}

impl RegistrationProof {
    /// Accept only an 80-byte sealed 32-byte challenge, never arbitrary files
    /// or a caller-selected key. Only native account registration uses this.
    pub fn answer(&self, ciphertext: &str) -> Result<String, String> {
        crate::ownership_proof::answer(&self.0, ciphertext)
    }
}

#[cfg(test)]
mod tests {
    use crate::ownership_proof::unseal;
    use base64::{engine::general_purpose::STANDARD, Engine};
    use crypto_box::SecretKey;

    #[test]
    fn malformed_challenges_are_rejected() {
        let key = SecretKey::from([7; 32]);
        for length in [0, 32, 79, 80, 81, 4096] {
            assert!(unseal(&key, &vec![0; length]).is_err());
        }
    }

    #[test]
    fn php_sodium_challenge_requires_the_exact_noise_private_key() {
        // Generated by PHP sodium_crypto_box_seal with scalarmult_base([7;32])
        // and plaintext [42;32]. Synthetic fixture: contains no real identity.
        let sealed = STANDARD.decode("8DIfR1QHN2/4AfRkZrvhe0WvAaRpw5OeOrLon1ZPgyQvWoNh6fgrsIrItUuKfme1FuAwkJ6mnygyPGpP+lMVVUbekNSo4eLcir+5joNTLpk=").unwrap();
        assert_eq!(
            unseal(&SecretKey::from([7; 32]), &sealed).unwrap(),
            STANDARD.encode([42; 32])
        );
        assert!(unseal(&SecretKey::from([8; 32]), &sealed).is_err());
        let mut modified = sealed;
        modified[40] ^= 1;
        assert!(unseal(&SecretKey::from([7; 32]), &modified).is_err());
    }
}
