export const toolDescriptions: Record<string, string> = {
  github: 'Repositories, pull requests and issues',
  stripe: 'Payments, customers and billing',
  figma: 'Design files and project context',
  gmail: 'Email search, reading and approved sending',
  google_calendar: 'Upcoming events and approved scheduling',
  google_drive: 'Drive files, Docs, Sheets and Slides',
  google_tasks: 'Task lists and approved new tasks',
  deepwiki: 'Public repository documentation',
  hackernews: 'Public technology stories and discussions',
  outlook_mail: 'Outlook messages and approved sending',
  outlook_calendar: 'Outlook events and approved scheduling',
  onedrive: 'OneDrive files and text',
  teams: 'Workplace chats and messages',
  sharepoint: 'Sites and document libraries',
  slack: 'Channels, messages and approved bot posts',
  notion: 'Shared pages and notes',
  linear: 'Teams, issues and approved issue creation',
};
