export const settings = { model: 'gpt-6-astra', effort: 'high', revision: 0, approvalPolicy: 'on-request', appliesTo: 'nextTurn' };
export const patch = JSON.stringify([{ path: '/Projects/iPhone/src/connection.ts', kind: { type: 'update' }, diff:
  '@@ -18,5 +18,7 @@\n export function reconnect(session: Session) {\n-  clearConversation();\n-  return connect(session.host);\n+  preserveConversation(session.id);\n+  return connect(session.host, {\n+    afterCursor: session.cursor,\n+  });\n }' }]);
export const items = [
  { id: 'u', turnId: 'demo', kind: 'message', role: 'user', text: 'Keep my conversation in place when my phone reconnects. Make sure my draft stays safe, too.', status: 'completed' },
  { id: 'a', turnId: 'demo', kind: 'message', role: 'assistant', text: 'I’ll trace the connection lifecycle, then make the smallest change that keeps your conversation and draft together.', status: 'completed' },
  { id: 'thinking', turnId: 'demo', kind: 'activity', category: 'reasoning', title: 'Thinking', detail: 'The session already has a durable identity. I’m checking where the view discards it during a temporary connection loss.', status: 'completed' },
  { id: 'read', turnId: 'demo', kind: 'activity', category: 'commandExecution', title: 'Reading files', command: 'cat src/connection.ts', detail: 'Read src/connection.ts and src/conversation.ts\nThe disconnect handler clears the active view before attempting reconnect.', durationMs: 124, status: 'completed' },
  { id: 'edit', turnId: 'demo', kind: 'activity', category: 'fileChange', title: 'Updating files', detail: patch, durationMs: 842, status: 'completed', artifact: { id: 'patch', hash: 'fixture', bytes: patch.length, truncated: false }, changes: [{ path: '/Projects/iPhone/src/connection.ts', kind: { type: 'update' }, added: 4, removed: 2 }] },
  { id: 'test', turnId: 'demo', kind: 'activity', category: 'commandExecution', title: 'Running command', command: 'npm test -- connection', detail: 'npm test -- connection\n✓ reconnect restores the same session\n✓ unsent drafts survive connection loss\n\n2 tests passed', exitCode: 0, durationMs: 1640, status: 'completed' },
  { id: 'answer', turnId: 'demo', kind: 'message', role: 'assistant', text: 'The conversation now stays in place during reconnect. Your draft, history position, and expanded activity stay with the same session.\n\n### What changed\n\n- Reconnect resumes from the last received cursor.\n- The draft remains attached to the original session.\n- Temporary connection loss keeps the conversation visible.\n\nBoth connection tests passed.\n\n```ts\nreturn connect(session.host, {\n  afterCursor: session.cursor,\n});\n```', status: 'completed' },
];
export const commands = ['help', 'status', 'usage', 'model', 'effort', 'permissions', 'diff', 'context'].map(name => ({ name, description: ({ help: 'Find a conversation command', status: 'Session and effective settings', usage: 'Account limits and conversation tokens', model: 'Choose a model', effort: 'Choose reasoning effort', permissions: 'Review execution policy and saved rules', diff: 'Inspect recorded file changes', context: 'Inspect observed context' } as Record<string, string>)[name], aliases: name === 'effort' ? ['reasoning'] : [], scope: ['model', 'effort'].includes(name) ? 'settings' : 'read', available: true }));
export const usage = { thread: { total: { totalTokens: 12840, inputTokens: 10720, cachedInputTokens: 8240, outputTokens: 2120 }, last: { totalTokens: 12840 } }, account: { rateLimits: { primary: { usedPercent: 32, windowDurationMins: 300 }, secondary: { usedPercent: 18, windowDurationMins: 10080 } } } };
