import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  hint: { fontSize: 13, lineHeight: 20, textAlign: 'center' },
  empty: { paddingVertical: 40, alignItems: 'center', gap: 10 },
  section: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    letterSpacing: -0.05,
    paddingTop: 22,
    paddingBottom: 6,
    paddingHorizontal: 10,
  },
  stick: { paddingHorizontal: 20, paddingBottom: 10 },
  search: {
    minHeight: 40,
    borderRadius: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  searchInput: { flex: 1, minHeight: 40, fontSize: 15, letterSpacing: -0.2, outlineWidth: 0 },
  clear: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  company: {
    minHeight: 68,
    paddingVertical: 12,
    paddingHorizontal: 10,
    flexDirection: 'row',
    gap: 13,
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  selection: {
    width: 21,
    height: 21,
    borderRadius: 11,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  auto: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  text: { flex: 1, gap: 2 },
  name: { fontSize: 15, lineHeight: 20, fontWeight: '600', letterSpacing: -0.25, flexShrink: 1 },
  detail: { fontSize: 13, lineHeight: 18 },
  blocked: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  blockedIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
