import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  desktop: { flex: 1 },
  grow: { flex: 1 },
  chrome: {
    height: 14,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  // The brand block is exactly as wide as the column under it, as in the app.
  brand: { width: '28%', flexDirection: 'row', alignItems: 'center', gap: 3, paddingLeft: 6 },
  light: { width: 4, height: 4, borderRadius: 2 },
  wordmark: { fontSize: 7, lineHeight: 9, fontWeight: '700', letterSpacing: -0.1, flexShrink: 1 },
  context: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 6 },
  stat: {
    width: 8,
    height: 8,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 2,
  },
  statDot: { width: 4, height: 4, borderRadius: 2 },
  body: { flex: 1, flexDirection: 'row' },
  rail: {
    width: '28%',
    borderRightWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 4,
    paddingTop: 5,
    gap: 2,
  },
  search: { height: 7, borderRadius: 3, marginBottom: 3 },
  row: {
    height: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 3,
    borderRadius: 3,
  },
  glyph: { width: 4, height: 4, borderRadius: 1, borderWidth: 1 },
  section: { paddingHorizontal: 3, paddingTop: 4, paddingBottom: 1 },
  dot: { width: 4, height: 4, borderRadius: 2 },
  bar: { height: 3, borderRadius: 1.5 },
  stage: { flex: 1, flexDirection: 'row', gap: 1 },
  pane: { flex: 1 },
  head: {
    height: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  badge: { width: 7, height: 7, borderRadius: 2, alignItems: 'center', justifyContent: 'center' },
  number: { fontSize: 5, lineHeight: 7, height: 7, textAlign: 'center', fontWeight: '800' },
  output: { flex: 1, paddingHorizontal: 5, paddingTop: 7, gap: 6 },
  line: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  indent: { paddingLeft: 6 },
  mark: { width: 3, height: 3, borderRadius: 1.5 },
  prompt: { height: 12, flexDirection: 'row', alignItems: 'center', gap: 2, paddingHorizontal: 4 },
  caret: { width: 4, height: 7, borderRadius: 1 },
  ring: { borderWidth: 1, opacity: 0.75 },
  taskbar: {
    height: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 7,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  running: { alignItems: 'center', gap: 1 },
  underline: { width: 5, height: 1, borderRadius: 1 },
});
