import type { ImageSourcePropType } from 'react-native';

// Bundled provider marks and creator avatars; provenance in assets/company-logos/sources.json.
export const companyArtwork: Record<string, { light: ImageSourcePropType; dark?: ImageSourcePropType }> = {
  'aion-labs': { light: require('../../assets/company-logos/aion-labs-light.png'), dark: require('../../assets/company-logos/aion-labs-dark.png') },
  'anthracite-org': { light: require('../../assets/company-logos/anthracite-org-light.png') },
  'arcee-ai': { light: require('../../assets/company-logos/arcee-ai-light.png'), dark: require('../../assets/company-logos/arcee-ai-dark.png') },
  'baidu': { light: require('../../assets/company-logos/baidu-light.png'), dark: require('../../assets/company-logos/baidu-dark.png') },
  'bytedance': { light: require('../../assets/company-logos/bytedance-light.png'), dark: require('../../assets/company-logos/bytedance-dark.png') },
  'cognitivecomputations': { light: require('../../assets/company-logos/cognitivecomputations-light.png'), dark: require('../../assets/company-logos/cognitivecomputations-dark.png') },
  'cohere': { light: require('../../assets/company-logos/cohere-light.png'), dark: require('../../assets/company-logos/cohere-dark.png') },
  'dots-studio': { light: require('../../assets/company-logos/dots-studio-light.png'), dark: require('../../assets/company-logos/dots-studio-dark.png') },
  'fireworks': { light: require('../../assets/company-logos/fireworks-light.png'), dark: require('../../assets/company-logos/fireworks-dark.png') },
  'gryphe': { light: require('../../assets/company-logos/gryphe-light.png') },
  'ibm-granite': { light: require('../../assets/company-logos/ibm-granite-light.png'), dark: require('../../assets/company-logos/ibm-granite-dark.png') },
  'inception': { light: require('../../assets/company-logos/inception-light.png'), dark: require('../../assets/company-logos/inception-dark.png') },
  'inclusionai': { light: require('../../assets/company-logos/inclusionai-light.png') },
  'inference-net': { light: require('../../assets/company-logos/inference-net-light.png'), dark: require('../../assets/company-logos/inference-net-dark.png') },
  'kwaipilot': { light: require('../../assets/company-logos/kwaipilot-light.png'), dark: require('../../assets/company-logos/kwaipilot-dark.png') },
  'liquid': { light: require('../../assets/company-logos/liquid-light.png'), dark: require('../../assets/company-logos/liquid-dark.png') },
  'mancer': { light: require('../../assets/company-logos/mancer-light.png') },
  'meituan': { light: require('../../assets/company-logos/meituan-light.png') },
  'morph': { light: require('../../assets/company-logos/morph-light.png'), dark: require('../../assets/company-logos/morph-dark.png') },
  'nousresearch': { light: require('../../assets/company-logos/nousresearch-light.png'), dark: require('../../assets/company-logos/nousresearch-dark.png') },
  'openrouter': { light: require('../../assets/company-logos/openrouter-light.png'), dark: require('../../assets/company-logos/openrouter-dark.png') },
  'perceptron': { light: require('../../assets/company-logos/perceptron-light.png'), dark: require('../../assets/company-logos/perceptron-dark.png') },
  'poolside': { light: require('../../assets/company-logos/poolside-light.png'), dark: require('../../assets/company-logos/poolside-dark.png') },
  'prism-ml': { light: require('../../assets/company-logos/prism-ml-light.png') },
  'rekaai': { light: require('../../assets/company-logos/rekaai-light.png'), dark: require('../../assets/company-logos/rekaai-dark.png') },
  'relace': { light: require('../../assets/company-logos/relace-light.png'), dark: require('../../assets/company-logos/relace-dark.png') },
  'sakana': { light: require('../../assets/company-logos/sakana-light.png'), dark: require('../../assets/company-logos/sakana-dark.png') },
  'sao10k': { light: require('../../assets/company-logos/sao10k-light.png') },
  'stealth': { light: require('../../assets/company-logos/stealth-light.png') },
  'stepfun': { light: require('../../assets/company-logos/stepfun-light.png'), dark: require('../../assets/company-logos/stepfun-dark.png') },
  'tencent': { light: require('../../assets/company-logos/tencent-light.png'), dark: require('../../assets/company-logos/tencent-dark.png') },
  'thedrummer': { light: require('../../assets/company-logos/thedrummer-light.png') },
  'thinkingmachines': { light: require('../../assets/company-logos/thinkingmachines-light.png') },
  'typesafe': { light: require('../../assets/company-logos/typesafe-light.png') },
  'unbiased': { light: require('../../assets/company-logos/unbiased-light.png') },
  'undi95': { light: require('../../assets/company-logos/undi95-light.png') },
  'upstage': { light: require('../../assets/company-logos/upstage-light.png'), dark: require('../../assets/company-logos/upstage-dark.png') },
  'writer': { light: require('../../assets/company-logos/writer-light.png') },
  'xiaomi': { light: require('../../assets/company-logos/xiaomi-light.png'), dark: require('../../assets/company-logos/xiaomi-dark.png') },
  'z-ai': { light: require('../../assets/company-logos/z-ai-light.png'), dark: require('../../assets/company-logos/z-ai-dark.png') },
};
