import { StyleSheet } from 'react-native';
import { font } from './font';

export const styles = StyleSheet.create({
  flow: { flex: 1 },
  content: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 36,
  },
  identity: { paddingTop: 22, alignItems: 'center' },
  name: { ...font.title, textAlign: 'center' },
  platform: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 6 },
  platformText: { ...font.subhead, flexShrink: 1 },
  status: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 14,
    minHeight: 28,
    paddingHorizontal: 12,
    borderRadius: 14,
  },
  dot: { width: 7, height: 7, borderRadius: 4 },
  statusText: { fontSize: 13, fontWeight: '600', flexShrink: 1 },
  facts: {
    marginTop: 26,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  fact: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    marginBottom: -StyleSheet.hairlineWidth,
  },
  factLong: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 12,
  },
  factLabel: { fontSize: 15, letterSpacing: -0.2 },
  factValue: { fontSize: 15, letterSpacing: -0.2, flexShrink: 1, fontVariant: ['tabular-nums'] },
  notice: { paddingTop: 16 },
  actions: { gap: 2, paddingTop: 22 },
  forget: { minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  forgetText: { fontSize: 15, fontWeight: '500' },
  note: { ...font.footnote, marginTop: 10, textAlign: 'center', paddingHorizontal: 12 },
});
