export type SettingsSectionId =
  | "general"
  | "ai"
  | "integrations"
  | "privacy"
  | "help"
  | "notifications"
  | "iphone"
  | "cloud"
  | "shortcuts"
  | "account"
  | "security"
  | "advanced";

/** A group inside a section that a deep link can open and scroll to. */
export type SettingsPanelId =
  | "appearance"
  | "performance"
  | "privacy"
  | "identity"
  | "membership"
  | "credits"
  | "security"
  | "devices"
  | "danger"
  | "data"
  | "activity"
  | "terminalAccounts"
  | "integrations"
  | "voice"
  | "terminal"
  | "files"
  | "graphics"
  | "runtimes"
  | "cloudStatus"
  | "cloudProjects"
  | "cloudAccounts" | "cloudCapacity"
  | "cloudComputer"
  | "cloudDelete";
