import React from "react";
import {spring, useCurrentFrame, useVideoConfig} from "remotion";
import {font, palette} from "../styles/tokens";
import {StatusDot} from "./DesktopTerminalPanels";

export const ModelPanel = () => {const frame = useCurrentFrame(); const {fps} = useVideoConfig(); return <div style={{height: "100%", padding: "26px 34px"}}>
  <div style={{display: "flex", justifyContent: "space-between"}}><div><div style={{color: palette.accentBright, fontSize: 12, fontWeight: 800, letterSpacing: 2}}>MODEL ROUTING</div><h3 style={{margin: "8px 0", fontSize: 30}}>Choose the right AI for each terminal.</h3></div><span style={{color: palette.success}}>Accounts connected</span></div>
  <div style={{display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14, marginTop: 26}}>{[["GPT-5 Codex", "Build"], ["Claude Sonnet", "Review"], ["Gemini", "Research"]].map(([model, task], index) => {const reveal = spring({frame: frame - index * 7, fps, config: {damping: 22, stiffness: 240}}); return <div key={model} style={{opacity: reveal, transform: `translateY(${(1 - reveal) * 30}px) rotateX(${(1 - reveal) * 8}deg)`, padding: 22, borderRadius: 14, border: `1px solid ${index === 0 ? palette.accent : palette.border}`, background: index === 0 ? "rgba(91,124,250,.12)" : palette.surface}}><div style={{display: "flex", alignItems: "center", gap: 10}}><StatusDot color={index === 0 ? palette.accentBright : palette.success} /><b style={{fontSize: 19}}>{model}</b></div><p style={{color: palette.muted}}>Assigned to {task}</p><div style={{fontSize: 12, color: index === 0 ? palette.accentBright : palette.success}}>{index === 0 ? "Selected" : "Available"}</div></div>;})}</div>
</div>;};

export const ReviewPanel = () => {const frame = useCurrentFrame(); const {fps} = useVideoConfig(); return <div style={{height: "100%", display: "grid", gridTemplateColumns: "1.55fr .75fr", gap: 12}}>
  <div style={{border: `1px solid ${palette.border}`, borderRadius: 14, overflow: "hidden", background: "#101217"}}><div style={{padding: "14px 18px", borderBottom: `1px solid ${palette.border}`, color: palette.muted}}>AnalyticsOverview.tsx <span style={{float: "right", color: palette.success}}>+48</span></div><div style={{padding: 22, fontFamily: font.mono, fontSize: 15, lineHeight: 1.75}}>{["export function AnalyticsOverview() {", "  const metrics = useAtlasMetrics();", "  return <MetricsGrid data={metrics} />;", "}"].map(line => <div key={line} style={{background: "rgba(55,199,138,.10)", color: "#bfe8d3"}}>+ {line}</div>)}</div></div>
  <div><div style={{padding: 22, borderRadius: 14, border: `1px solid ${palette.border}`, background: palette.surface}}><div style={{color: palette.success, fontSize: 13, fontWeight: 800}}>ALL CHECKS PASSED</div><h3 style={{margin: "9px 0 16px", fontSize: 28}}>Ready to review</h3>{["3 files changed", "8 tests passed", "Preview ready"].map((item, index) => {const reveal = spring({frame: frame - 8 - index * 7, fps, config: {damping: 24, stiffness: 230}}); return <div key={item} style={{opacity: reveal, transform: `translateX(${(1 - reveal) * 22}px)`, marginTop: 10, display: "flex", gap: 9, alignItems: "center", color: palette.muted}}><StatusDot />{item}</div>;})}</div></div>
</div>;};
