import React from "react";
import {interpolate, useCurrentFrame} from "remotion";
import {clamp} from "../motion/timing";
import {font, palette} from "../styles/tokens";

type Screen = "projects" | "prompt" | "activity" | "approve" | "preview";

const Status = () => <div style={{display: "flex", alignItems: "center", gap: 7, color: palette.success, fontSize: 13}}><span style={{width: 7, height: 7, borderRadius: 99, background: palette.success}} />Desktop connected</div>;
const Header = ({title}: {title: string}) => <><div style={{display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 22}}><b style={{fontSize: 21}}>{title}</b><div style={{width: 32, height: 32, borderRadius: 99, background: palette.elevated, display: "grid", placeItems: "center", color: palette.accentBright}}>E</div></div><Status /></>;

const Projects = () => <><Header title="Projects" /><div style={{marginTop: 24, padding: 18, borderRadius: 16, border: `1px solid ${palette.accent}`, background: "rgba(91,124,250,.12)"}}><div style={{display: "flex", justifyContent: "space-between"}}><b style={{fontSize: 18}}>Atlas</b><span style={{color: palette.success, fontSize: 12}}>Active</span></div><p style={{color: palette.muted, fontSize: 13, lineHeight: 1.5}}>Bookings dashboard · Desktop</p></div><div style={{marginTop: 12, padding: 16, borderRadius: 16, border: `1px solid ${palette.border}`, color: palette.muted}}>Vibyra website</div></>;
const Prompt = () => <><Header title="Atlas" /><div style={{marginTop: 52, color: palette.muted, textAlign: "center", fontSize: 15}}>What should Vibyra build?</div><div style={{marginTop: 170, padding: 16, borderRadius: 18, background: palette.elevated, border: `1px solid ${palette.border}`, lineHeight: 1.45, fontSize: 15}}>Add the analytics overview, test it, and open a preview.<div style={{display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 18, color: palette.muted, fontSize: 12}}><span>GPT-5 · High</span><span style={{width: 38, height: 38, display: "grid", placeItems: "center", borderRadius: 12, color: "white", background: palette.action}}>↑</span></div></div></>;
const Activity = () => <><Header title="Atlas is building" />{[["Plan created", "Done"], ["6 terminals working", "Live"], ["3 files changed", "Review"], ["Preview server", "Ready"]].map(([label, state], i) => <div key={label} style={{display: "flex", justifyContent: "space-between", marginTop: i ? 10 : 26, padding: 15, borderRadius: 14, background: palette.surface, border: `1px solid ${i === 1 ? palette.accent : palette.border}`}}><span>{label}</span><span style={{color: state === "Live" ? palette.accentBright : palette.success, fontSize: 12}}>{state}</span></div>)}</>;
const Approve = ({pressed}: {pressed: boolean}) => <><Header title="Review changes" /><div style={{marginTop: 26, padding: 17, borderRadius: 16, background: palette.surface, border: `1px solid ${palette.border}`}}><b>3 files changed</b>{["AnalyticsOverview.tsx", "analytics.css", "AnalyticsOverview.test.tsx"].map((file) => <div key={file} style={{marginTop: 13, color: palette.muted, fontFamily: font.mono, fontSize: 12}}>+ {file}</div>)}</div><div style={{display: "flex", gap: 10, marginTop: 20}}><div style={{flex: 1, padding: 14, textAlign: "center", border: `1px solid ${palette.border}`, borderRadius: 13}}>Deny</div><div style={{flex: 1, padding: 14, textAlign: "center", borderRadius: 13, color: "white", background: pressed ? palette.success : palette.action, transform: `scale(${pressed ? .96 : 1})`}}>{pressed ? "Approved" : "Approve"}</div></div></>;
const Preview = () => <><Header title="Atlas preview" /><div style={{marginTop: 18, padding: 16, borderRadius: 18, background: "#f7f8fa", color: "#161920", minHeight: 430}}><b style={{fontSize: 22}}>Analytics overview</b><p style={{color: "#697180", fontSize: 12}}>Last 30 days</p><div style={{display: "flex", gap: 8}}>{[["Bookings", "842"], ["Revenue", "£48k"], ["Conversion", "12.4%"]].map(([a,b]) => <div key={a} style={{flex: 1, padding: 10, borderRadius: 10, background: "white", boxShadow: "0 5px 18px rgba(0,0,0,.07)"}}><small style={{color: "#727987"}}>{a}</small><div style={{fontWeight: 760, marginTop: 5}}>{b}</div></div>)}</div><div style={{height: 190, marginTop: 22, borderRadius: 13, background: "linear-gradient(180deg,rgba(91,124,250,.18),rgba(91,124,250,.02))", display: "flex", alignItems: "end", gap: 9, padding: 18}}>{[45,70,52,88,66,94,78].map((h,i) => <span key={i} style={{flex: 1, height: `${h}%`, borderRadius: 7, background: i === 5 ? palette.accent : "#afbcf7"}} />)}</div></div></>;

export const PhoneFrame: React.FC<{screen: Screen; style?: React.CSSProperties}> = ({screen, style}) => {
  const frame = useCurrentFrame();
  const pressed = screen === "approve" && interpolate(frame, [125, 135], [0, 1], clamp) > .5;
  return <div style={{width: 390, height: 800, padding: 14, borderRadius: 58, background: "linear-gradient(145deg,#303640,#090a0d)", boxShadow: "0 45px 110px rgba(0,0,0,.68),0 0 46px rgba(91,124,250,.24)", ...style}}><div style={{height: "100%", padding: "48px 24px 24px", borderRadius: 45, overflow: "hidden", background: palette.canvas, border: "1px solid rgba(255,255,255,.1)", color: palette.text, fontFamily: font.sans}}>{screen === "projects" ? <Projects /> : screen === "prompt" ? <Prompt /> : screen === "activity" ? <Activity /> : screen === "approve" ? <Approve pressed={pressed} /> : <Preview />}</div></div>;
};
