import assert from "node:assert/strict";
import { show } from "./teammateModalChecks.mjs";
export async function saveChecks(page, results) {
  await show(page,"agent");
  await page.evaluate(() => window.qa.faults.agent_profile_list="reject");
  await page.getByLabel(/Name/).fill("Saved once");
  await page.getByRole("button",{name:"Create teammate"}).click();
  await page.waitForFunction(() => window.qa.stores().selected?.startsWith("created-"));
  assert.equal(await page.evaluate(() => window.qa.native.calls.agent_profile_create),1);
  assert.equal(await page.evaluate(() => window.qa.stores().agents.filter(x=>x.name==="Saved once").length),1);
  results.push("Successful create is visible without depending on roster refresh");
  for (const kind of ["routine","skill"]) {
    await show(page,kind,true);
    const command=kind==="routine"?"routine_update":"skill_revise";
    await page.evaluate(command=>window.qa.faults[command]="delay",command);
    await page.locator('button[type="submit"]').click();
    await page.waitForFunction(command=>window.qa.native.calls[command]===1,command);
    assert.equal(await page.locator('button[type="submit"]').isDisabled(),true);
    await page.locator('form').evaluate(el=>el.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
    assert.equal(await page.evaluate(command=>window.qa.native.calls[command],command),1);
    await page.evaluate(command=>window.qa.release(command),command);
    await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
    results.push(`${kind} repeated submit sends one pending write`);
  }
  await show(page,"assignment");
  const checkbox=page.getByRole('checkbox');
  await checkbox.waitFor(); await page.waitForFunction(()=>!document.querySelector('[type="checkbox"]').disabled);
  await page.evaluate(()=>window.qa.faults.skill_assign="reject");
  await checkbox.click();
  await page.getByRole('alert').waitFor();
  assert.equal(await checkbox.isChecked(),false);
  await page.evaluate(()=>delete window.qa.faults.skill_assign);
  await checkbox.click(); await page.waitForFunction(()=>document.querySelector('[type="checkbox"]').checked);
  await page.evaluate(()=>window.qa.render("assignment"));
  await page.waitForFunction(()=>document.querySelector('[type="checkbox"]').checked);
  results.push("Failed skill assignment retains confirmed state; retry survives reopening");
  await show(page,"memory");
  const field=page.getByPlaceholder("Something this teammate should always know");
  await field.fill("Remember this failed draft");
  await page.evaluate(()=>window.qa.faults.agent_memory_add="reject");
  await page.getByRole('button',{name:'Add',exact:true}).click(); await page.getByRole('alert').waitFor();
  assert.equal(await field.inputValue(),"Remember this failed draft");
  await page.evaluate(()=>{delete window.qa.faults.agent_memory_add; window.qa.faults.agent_memory_list="reject";});
  await page.getByRole('button',{name:'Add',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.memory-add input').value==='');
  assert.equal(await page.evaluate(()=>window.qa.stores().memory['qa-agent'].length),1);
  results.push("Failed memory save preserves text; successful retry survives refresh failure");
  await field.fill("First submitted note");
  await page.evaluate(()=>window.qa.faults.agent_memory_add="delay");
  await page.getByRole('button',{name:'Add',exact:true}).click();
  await page.waitForFunction(()=>window.qa.native.calls.agent_memory_add===3);
  await field.fill("Newer unsaved note");
  await page.evaluate(()=>window.qa.release("agent_memory_add"));
  await page.waitForFunction(()=>!document.querySelector('.memory-add button').disabled);
  assert.equal(await field.inputValue(),"Newer unsaved note");
  results.push("Late memory success does not clear newer typing");
  await show(page,"agent");
  await page.getByLabel(/Name/).fill("Recovered save");
  await page.evaluate(()=>window.qa.faults.agent_profile_create="lost");
  await page.getByRole('button',{name:'Create teammate'}).click(); await page.getByRole('alert').waitFor();
  await page.evaluate(()=>delete window.qa.faults.agent_profile_create);
  await page.getByRole('button',{name:'Create teammate'}).click();
  await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
  assert.equal(await page.evaluate(()=>window.qa.native.calls.agent_profile_create),1);
  assert.equal(await page.evaluate(()=>window.qa.stores().agents.filter(x=>x.name==='Recovered save').length),1);
  results.push("Lost create response reconciles the receipt without another write");
  await show(page,"agent");
  await page.getByLabel(/Name/).fill("Background save");
  await page.evaluate(()=>window.qa.faults.agent_profile_create="delay");
  await page.getByRole('button',{name:'Create teammate'}).click();
  await page.waitForFunction(()=>window.qa.native.calls.agent_profile_create===1);
  await page.getByRole('button',{name:'Close',exact:true}).last().click();
  await page.evaluate(()=>window.qa.release("agent_profile_create"));
  await page.waitForFunction(()=>window.qa.stores().agents.some(x=>x.name==='Background save'));
  assert.equal(await page.locator('[role="dialog"]').count(),0);
  results.push("Closing during save preserves the result without reopening the form");
}
