import assert from "node:assert/strict";
import { show } from "./teammateModalChecks.mjs";
export async function recoveryChecks(page, results) {
  await show(page,"agent");
  await page.evaluate(()=>{window.qa.faults.agent_profile_list="delay"; void window.qa.loadRoster();});
  await page.waitForFunction(()=>window.qa.native.calls.agent_profile_list===2);
  // A probe/list refresh is allowed to complete before submitting; exercise
  // the store directly here to force the dangerous refresh-before-write order.
  await page.evaluate(()=>window.qa.createDirect("Newer saved teammate"));
  await page.evaluate(()=>window.qa.release("agent_profile_list"));
  await page.waitForFunction(()=>window.qa.stores().agents.some(x=>x.name==="Newer saved teammate"));
  assert.equal(await page.evaluate(()=>window.qa.stores().agents.length),2);
  results.push("Stale roster response cannot overwrite a newer committed teammate");
  await show(page,"agent");
  await page.getByLabel(/Name/).fill("Previous account save");
  await page.evaluate(()=>window.qa.faults.agent_profile_create="delay");
  await page.getByRole("button",{name:"Create teammate"}).click();
  await page.waitForFunction(()=>window.qa.native.calls.agent_profile_create===1);
  await page.evaluate(()=>{window.qa.account("another-account");window.qa.release("agent_profile_create");});
  await page.getByRole('alert').waitFor();
  assert.equal(await page.evaluate(()=>window.qa.stores().agents.length),0);
  results.push("Late save from previous account cannot populate the current account");
  await show(page,"agent");
  await page.getByLabel(/Name/).fill("Background failure");
  await page.evaluate(()=>window.qa.faults.agent_profile_create="delay");
  await page.getByRole("button",{name:"Create teammate"}).click();
  await page.waitForFunction(()=>window.qa.native.calls.agent_profile_create===1);
  await page.getByRole("button",{name:"Close",exact:true}).last().click();
  await page.evaluate(()=>{window.qa.release("agent_profile_create");window.qa.faults.agent_profile_create="reject";});
  await page.waitForFunction(()=>!!window.qa.stores().error);
  assert.match(await page.evaluate(()=>window.qa.stores().error), /failed/);
  results.push("A failed background save remains visible after the form closes");
  await show(page,"agent");
  await page.getByLabel(/Name/).fill("Late confirmation");
  await page.evaluate(()=>window.qa.faults.agent_profile_create="delay");
  await page.getByRole("button",{name:"Create teammate"}).click();
  await page.getByRole("alert").filter({hasText:"not been confirmed"}).waitFor({timeout:20_000});
  await page.getByRole("button",{name:"Create teammate"}).click();
  await page.getByRole("alert").filter({hasText:"still saving"}).waitFor();
  assert.equal(await page.evaluate(()=>window.qa.native.calls.agent_profile_create),1);
  await page.evaluate(()=>window.qa.release("agent_profile_create"));
  await page.waitForFunction(()=>window.qa.stores().agents.some(x=>x.name==="Late confirmation"));
  await page.getByRole("button",{name:"Create teammate"}).click();
  await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
  assert.equal(await page.evaluate(()=>window.qa.native.calls.agent_profile_create),1);
  assert.equal(await page.evaluate(()=>window.qa.stores().agents.filter(x=>x.name==="Late confirmation").length),1);
  results.push("A timeout followed by late success reconciles the original form without duplicate creation");
  await show(page,"agent");
  await page.getByLabel(/Name/).fill("Reload recovery");
  await page.evaluate(()=>window.qa.faults.agent_profile_create="lost");
  await page.getByRole("button",{name:"Create teammate"}).click(); await page.getByRole('alert').waitFor();
  const snapshot=await page.evaluate(()=>window.qa.native);
  await page.addInitScript(snapshot=>{window.__AUDIT_NATIVE_SNAPSHOT__=snapshot;},snapshot);
  await page.reload(); await page.waitForFunction(()=>!!window.qa);
  await page.evaluate(()=>window.qa.render("agent"));
  await page.locator('#opener').click(); await page.getByLabel(/Name/).fill("Reload recovery");
  await page.getByRole("button",{name:"Create teammate"}).click();
  await page.waitForFunction(()=>!document.querySelector('[role="dialog"]'));
  assert.equal(await page.evaluate(()=>window.qa.native.calls.agent_profile_create),1);
  assert.equal(await page.evaluate(()=>window.qa.stores().agents.filter(x=>x.name==="Reload recovery").length),1);
  results.push("Renderer reload reconciles a lost response using the persisted token");
}
