import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  browser: {
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#FBFBF7',
    borderColor: '#DADDD6',
    borderWidth: StyleSheet.hairlineWidth,
  },
  address: {
    backgroundColor: '#EFF0EA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    padding: 12,
  },
  addressText: { fontSize: 11, color: '#686F65' },
  store: { padding: 22 },
  storeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 33,
  },
  wordmark: { fontSize: 25, letterSpacing: -1.1, fontWeight: '600', color: '#252B27' },
  eyebrow: { fontSize: 9, letterSpacing: 1.2, color: '#626B60', fontWeight: '500' },
  headline: {
    color: '#252B27',
    fontSize: 30,
    lineHeight: 38,
    fontWeight: '500',
    letterSpacing: -1.2,
    marginTop: 10,
  },
  description: { color: '#626B60', fontSize: 12, lineHeight: 20, marginTop: 5 },
  product: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 27, marginBottom: 24 },
  productArt: {
    width: 80,
    height: 93,
    borderRadius: 12,
    backgroundColor: '#ECEFE7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  book: {
    width: 46,
    height: 63,
    backgroundColor: '#829583',
    borderRadius: 3,
    transform: [{ rotate: '-10deg' }],
    padding: 7,
    justifyContent: 'space-between',
  },
  bookSpine: {
    position: 'absolute',
    left: 3,
    width: 1,
    top: 0,
    bottom: 0,
    backgroundColor: '#647965',
  },
  bookLabel: { fontSize: 5, lineHeight: 7, color: '#FCFBED', marginTop: 11 },
  bookDot: { height: 4, width: 4, borderRadius: 2, backgroundColor: '#FCFBED' },
  productInfo: { flex: 1, gap: 7 },
  productName: { fontSize: 13, lineHeight: 20, fontWeight: '500', color: '#252B27' },
  productDetail: { fontSize: 11, color: '#626B60' },
  productPrice: { fontSize: 12, fontWeight: '500', color: '#252B27', marginTop: 3 },
  summary: {
    gap: 13,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#DADDD6',
    paddingTop: 20,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  summaryLabel: { fontSize: 12, color: '#626B60' },
  summaryValue: { fontSize: 12, color: '#252B27' },
  total: {
    paddingTop: 14,
    marginTop: 1,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#DADDD6',
  },
  totalText: { fontSize: 16, color: '#252B27', fontWeight: '500' },
  checkout: {
    minHeight: 47,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    backgroundColor: '#344D3D',
    borderRadius: 12,
    marginTop: 22,
    paddingHorizontal: 10,
  },
  checkoutText: { fontSize: 12, color: '#FFFFFF', fontWeight: '500', flexShrink: 1 },
  sampleNote: {
    fontSize: 9,
    lineHeight: 15,
    textAlign: 'center',
    color: '#626B60',
    paddingTop: 13,
  },
  feedbackLabel: { fontSize: 17, fontWeight: '600', marginTop: 8 },
  input: {
    fontSize: 16,
    lineHeight: 24,
    minHeight: 96,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 18,
    padding: 17,
    textAlignVertical: 'top',
  },
});
