import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 20, paddingBottom: 28, gap: 24 },
  user: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    maxWidth: '88%',
    alignSelf: 'flex-end',
    marginLeft: 20,
  },
  message: { fontSize: 16, lineHeight: 24, letterSpacing: -0.2 },
  response: { gap: 12 },
  author: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  authorText: { fontSize: 14, fontWeight: '600', letterSpacing: -0.2 },
  provider: {
    fontSize: 11,
    fontWeight: '600',
    overflow: 'hidden',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: 1,
  },
  permission: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 14,
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  artifact: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 14,
    marginTop: 4,
    overflow: 'hidden',
  },
  result: {
    minHeight: 66,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  fileIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resultText: { flex: 1, gap: 2 },
  resultTitle: { fontSize: 15, fontWeight: '600', letterSpacing: -0.25 },
  fileName: { fontSize: 13, letterSpacing: -0.05 },
  needed: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  neededDot: { width: 6, height: 6, borderRadius: 3 },
  diff: { flexDirection: 'row', gap: 6, marginRight: 2 },
  diffText: { fontSize: 13, fontWeight: '600', fontVariant: ['tabular-nums'] },
  preview: {
    minHeight: 48,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  previewText: { flex: 1, fontSize: 15, fontWeight: '500', letterSpacing: -0.2 },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 10, paddingBottom: 50 },
  emptyTitle: {
    fontSize: 24,
    lineHeight: 30,
    letterSpacing: -0.6,
    fontWeight: '700',
    marginTop: 8,
  },
  emptyDetail: { fontSize: 15, letterSpacing: -0.2 },
});
