// Dated first-party-source snapshot. A cross means not listed, never proven absence.
// Recheck official sources and public release statuses before publishing an updated snapshot.
export const REVIEW_DATE = "30 September 2026";
export const COMPETITORS = [
    {"name": "BridgeMind", "url": "https://www.bridgemind.ai/", "platforms": "Mac · Windows · Linux", "price": "$25 promo · $50 list", "priceNote": "Promo through 1 Oct 2026", "values": ["y:Local workspace", "y:Multi-agent panes", "n", "n", "n", "n", "n", "y:Browser preview"], "sources": ["https://www.bridgemind.ai/"]},
    {"name": "Superset", "stack": "Electron", "url": "https://superset.sh/", "platforms": "macOS · iPhone", "price": "Free; Pro $20 / month", "priceNote": "Remote access/mobile require Pro", "values": ["y:Linux experimental", "y:Run agents in parallel", "y:iOS 26 · Pro", "n", "y:Cloud workspaces", "y:Worktrees + PRs", "y:Built-in editor", "y:Dev servers"], "sources": ["https://docs.superset.sh/install", "https://docs.superset.sh/editor", "https://docs.superset.sh/workspaces", "https://superset.sh/pricing"]},
    {"name": "Omnara", "url": "https://www.omnara.co/", "platforms": "Desktop · iOS · Android", "price": "Free", "priceNote": "Published offer", "values": ["y:Desktop app", "y:Parallel agents", "y:iOS + Android", "n", "y:Cloud migration", "y:Worktrees + diffs", "n", "n"], "sources": ["https://www.omnara.co/"]},
    {"name": "Conductor", "stack": "Tauri", "url": "https://www.conductor.build/", "platforms": "macOS · cloud", "price": "Free; Pro $50 / month", "priceNote": "Teams $60 / user / month", "values": ["y:macOS", "y:Parallel agents", "p:Mobile coming", "n", "y:Managed microVMs", "y:Workspaces + PRs", "y:Edit files in diffs", "n"], "sources": ["https://www.conductor.build/pricing", "https://www.conductor.build/docs/cloud/faq"]},
    {"name": "Sourceweave", "stack": "Tauri", "url": "https://sourceweave.app/", "platforms": "Mac · Windows · Linux", "price": "$20 / month", "priceNote": "$200 yearly", "values": ["y:Full IDE", "y:Agent Swarms", "y:Android companion", "n", "n:Local-first", "y:Tasks + PRs", "y:Built-in IDE", "y:Browser preview"], "sources": ["https://sourceweave.app/", "https://sourceweave.app/pricing"]},
    {"name": "VibeWorkspace", "stack": "Tauri", "url": "https://www.vibe-workspace.cloud/", "platforms": "Mac · Windows · Linux", "price": "Free or $10 lifetime", "priceNote": "Official pages conflict", "values": ["y:Local workspace", "y:Multi-agent terminals", "p:Remote control soon", "n", "n", "y:Git diffs", "y:Editor", "y:Browser preview"], "sources": ["https://www.vibe-workspace.cloud/features", "https://www.vibe-workspace.cloud/pricing", "https://www.vibe-workspace.cloud/downloads"]},
    {"name": "CLIMonkey", "stack": "Electron", "url": "https://climonkey.com/", "platforms": "Mac · Windows · Linux", "price": "Rp 499,000 / year", "priceNote": "Promotional price", "values": ["y:Terminal grid", "y:Side-by-side agents", "n", "n", "n", "y:Review + worktrees", "y:Code editor", "y:Browser preview"], "sources": ["https://climonkey.com/"]},
    {"name": "Nimbalyst", "stack": "Electron", "url": "https://nimbalyst.com/product/", "platforms": "Mac · Windows · Linux · iOS", "price": "Free; Teams $20 / user / month", "priceNote": "Teams currently in beta", "values": ["y:Local agents", "y:Parallel sessions", "y:iOS", "n", "n", "y:Worktrees + diffs", "y:Visual tools", "y:Chromium pane"], "sources": ["https://nimbalyst.com/product/", "https://nimbalyst.com/pricing/"]},
    {"name": "Radian", "url": "https://www.withradian.com/", "platforms": "Desktop · private beta", "price": "Not announced", "priceNote": "Cloud is early access", "values": ["p:Private beta", "y:Parallel tasks", "n:Browser access", "n", "p:Cloud early access", "y:Threads + diffs", "n", "n"], "sources": ["https://www.withradian.com/", "https://www.withradian.com/docs/cloud"]},
    {"name": "Junction", "stack": "Browser", "url": "https://junctionpanel.dev/", "platforms": "Browser control plane", "price": "Free; Core $10 / month", "priceNote": "Switchboard $15 / month", "values": ["y:Browser workspace", "y:Multiple agent sessions", "y:Relay to daemon/VPS", "n", "n:Own machine / VPS", "y:Diffs + checkpoints", "n:File browser", "n"], "sources": ["https://junctionpanel.dev/"]},
    {"name": "MeshCode", "stack": "Native", "url": "https://meshcode.ai/", "platforms": "Mac · Windows", "price": "Free", "priceNote": "Built-in model balance from $1", "values": ["y:Multi-pane", "y:Side-by-side agents", "n", "y:Built-in model balance", "p:Cloud sandbox in verification", "n", "n", "n"], "sources": ["https://meshcode.ai/"]},
    {"name": "Agent Workspace", "url": "https://agent-workspace.ai/", "platforms": "Mac · Windows · Linux", "price": "Free / source says MIT", "priceNote": "Repo private; access/build availability limited", "values": ["y:Any CLI", "y:Parallel sessions", "n", "n", "n", "y:Worktrees + PR links", "n", "n"], "sources": ["https://agent-workspace.ai/"]},
    {"name": "Dorchestrator", "url": "https://dorchestrator.app/", "platforms": "Waitlist · in development", "price": "$19 / month or $149 lifetime", "priceNote": "Listed offer; waitlist status", "values": ["p:In development", "p:Swarm feature advertised", "n", "n", "n", "n:Kanban review", "n", "n"], "sources": ["https://dorchestrator.app/"]},
    {"name": "Agent Orchestrator", "stack": "Electron", "url": "https://github.com/Untrivial-ai/agent-orchestrator", "platforms": "Mac · Windows · Linux", "price": "Free / open source", "priceNote": "25+ agent adapters", "values": ["y:Desktop app", "y:Parallel tasks", "y:Expo companion", "n", "u:Cloud scope not publicly verified", "y:Worktrees + PR/CI", "n", "y:Browser preview"], "sources": ["https://docs.aoagents.dev/", "https://github.com/Untrivial-ai/agent-orchestrator"]},
    {"name": "Dream", "stack": "Electron", "url": "https://dreamide.dev/", "platforms": "Mac · Windows · Linux", "price": "Free / open source", "priceNote": "Bring provider account", "values": ["y:Full IDE", "y:Multi-agent", "n", "n", "n", "y:Diffs + PR checks", "y:Editor", "y:Browser preview"], "sources": ["https://dreamide.dev/", "https://github.com/dreamide/dream"]},
    {"name": "GridTerm", "url": "https://gridterm.com/", "platforms": "Mac · Windows", "price": "$67 one-time", "priceNote": "Lifetime updates", "values": ["y:Up to 3×3", "y:Up to 3×3 sessions", "n", "n", "n", "n", "y:File editor", "n"], "sources": ["https://gridterm.com/"]},
    {"name": "Clodex", "stack": "Electron", "url": "https://useclodex.com/", "platforms": "Mac · Windows", "price": "From $15 / month", "priceNote": "Yearly plans available", "values": ["y:Claude + Codex", "y:Parallel agents", "n", "n", "n", "n", "y:Visual web editing", "y:Live web preview"], "sources": ["https://useclodex.com/"]},
    {"name": "AQ / AgentQueue", "stack": "Browser", "url": "https://www.agentqueue.dev/", "platforms": "Browser · cloud", "price": "$0; Teams $50 promo / user / month", "priceNote": "$200 list; $10 Composer credits / seat", "values": ["y:Browser workspace", "y:Parallel task workspaces", "n:Mobile browser", "y:AQ Composer + credits", "y:Private AQ VM or your cloud", "y:Worktrees + PRs", "y:Editor", "y:Live app preview"], "sources": ["https://www.agentqueue.dev/", "https://www.agentqueue.dev/pricing/"]},
];

export const VIBYRA_FEATURES = [
    "y:Desktop workspace", "y:Multiple terminals", "y:iPhone app",
    "y:Vibyra AI wallet", "y:Cloud VM", "y:Git review + worktrees",
    "y:Full IDE", "y:Desktop preview",
];

// [label, short column label, description]
export const FEATURES = [
    ["Agent workspace", "Agent workspace", "A desktop application or browser workspace for coding agents."],
    ["Parallel agents", "Parallel agents", "Several coding-agent sessions can run at the same time; this does not imply coordinated swarms."],
    ["Phone app", "Phone app", "A native iPhone or Android app, or phone access to agents running on your own computer."],
    ["Built-in AI credits", "Built-in AI credits", "First-party AI with its own credits or wallet, so you don’t need a separate provider account."],
    ["Cloud agents", "Cloud agents", "Agents run on vendor-hosted machines, so work continues with your laptop closed."],
    ["Worktrees / diff review", "Worktrees + review", "Isolated Git worktrees or built-in change review."],
    ["Editor / visual tools", "Editor", "A built-in code editor, full IDE, or visual editing tools."],
    ["Project preview", "Live preview", "A built-in browser or development-server preview."],
];

