export const HERO_TERMINALS = [
  {
    id: "claude",
    name: "Claude",
    tab: "Terminal 1 · Claude",
    runtime: "Claude Code",
    dot: "bg-[#d5a47a]",
    command: "claude \"Fix the mobile checkout layout\"",
    task: "Make the checkout usable below 480px without changing desktop behavior.",
    file: "src/components/Checkout.tsx",
    branch: "safe/checkout-mobile",
    elapsed: "18.4s",
    activity: [
      ["read", "Checkout.tsx", "components mapped"],
      ["edit", "Checkout.tsx", "+8 −3"],
      ["test", "checkout.test.tsx", "18 passed"],
    ],
    code: [
      ["41", " ", "<main className=\"checkout-shell\">"],
      ["42", "+", "  <section className=\"checkout-form\">"],
      ["43", "+", "    <OrderForm />"],
      ["44", "+", "  </section>"],
      ["45", " ", "  <OrderSummary />"],
      ["46", " ", "</main>"],
    ],
    result: "Component structure updated",
    detail: "18 tests passed · no desktop regression",
  },
  {
    id: "codex",
    name: "Codex",
    tab: "Terminal 2 · Codex",
    runtime: "OpenAI Codex",
    dot: "bg-violet",
    command: "codex \"Finish responsive styles and verify\"",
    task: "Stack the checkout columns and validate the 390px preview.",
    file: "src/styles/checkout.css",
    branch: "safe/checkout-mobile",
    elapsed: "12.7s",
    activity: [
      ["read", "checkout.css", "breakpoints found"],
      ["edit", "checkout.css", "+7 −1"],
      ["preview", "localhost:3000", "390 × 844 passed"],
    ],
    code: [
      ["88", "+", "@media (max-width: 480px) {"],
      ["89", "+", "  .checkout-shell {"],
      ["90", "+", "    grid-template-columns: 1fr;"],
      ["91", "+", "  }"],
      ["92", "+", "  .order-summary { position: static; }"],
      ["93", "+", "}"],
    ],
    result: "Mobile preview verified",
    detail: "390 × 844 · no overflow · ready to review",
  },
];
