import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/node_modules/@fontsource-variable/inter/index.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/node_modules/@fontsource-variable/jetbrains-mono/index.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/tokens.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base-controls.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base-badges.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base-scrollbars.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base-motion.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base-performance.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base-activity-dots.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/base-tooltips.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/controls.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/nav-segmented.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/chrome.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/chrome-nav.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/chrome-resize.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/chrome-account.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-bell.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-card.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-backdrop.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-choices.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-reveal.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-status.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-overrides.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-email.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/auth-email-form.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/first-welcome.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/first-welcome-motion.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/strip.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-menu.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-activity.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-dialogs.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-new.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-new-steps.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-new-browse.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-new-review.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/project-new-build.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/home.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/home-launch.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/home-cards.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/home-empty.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/home-recents.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/rail.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/rail-files.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/rail-footer.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/rail-sessions.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/launch-settings.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/launch-controls.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/launch-model-picker.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/launch-approval.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-shell.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-surface.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-chat-rail.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-transcript.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-answer.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-code-block.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-tools.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-turn.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-changed.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-composer.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-panels.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-lists.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-dashboard.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-decisions.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-work.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-unattended.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-provenance.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-skills.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-settings.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-memory.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-extras.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-mail.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/workspace.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/workspace-pane.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/workspace-pane-states.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/workspace-empty.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/workspace-voice-hud.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/workspace-shot-tray.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-pinned.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-toast.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-toast-content.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-toast-prompt.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-toast-motion.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-toast-progress.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-center.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-center-empty.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/notifications-center-row.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/preview.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/preview-picker.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/preview-device.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/preview-overlay.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-mark.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-picker.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/agent-picker-models.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/dock-shell.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/dock-panels.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/dock-review.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/dock-fleet.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/dock-fleet-row.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/dock-fleet-radar.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/review-diff.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/review-diff-rows.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/review-actions.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/review-changeset.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/review-conflict.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/review-github.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/review-verbs.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/companion-files.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/palette.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/palette-rows.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/modals.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-modal.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-pane.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-rows.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-agents.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-shortcuts.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-theme-cards.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-modal-narrow.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/kbd.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/terminal-suspended.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-ai-key.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-ai-uses.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-ai-usage.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-ai-guards.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-integrations.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-github-integration.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-account-connect.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-account-switch.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-integration-accounts.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-terminal-integrations.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-notifications.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-workspaces.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-choices.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-fields.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-attachments.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-context.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-footer.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-sent.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-entry.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/report-files.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/screenshot-editor.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/screenshot-controls.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/screenshot-tray.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-graphics.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-performance.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-updates.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-vault.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/companion-ask.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/companion-ask-workspace.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/companion-ask-voice.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/companion-ask-composer.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-hotkeys.css";
import "/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/styles/settings-profile.css";
import React from 'react';
import { createRoot } from 'react-dom/client';
import { AgentMode } from '/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/components/agentMode/AgentMode.tsx';
import { useAgentModeStore as mode } from '/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/state/agentModeStore.ts';
import { useAgentRosterStore as roster } from '/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/state/agentRosterStore.ts';
import { useAgentWorkStore as work } from '/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/state/agentWorkStore.ts';
import { useAgentChatStore as chat } from '/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/state/agentChatStore.ts';
import { useAgentAttachmentStore as attachments } from '/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/state/agentAttachmentStore.ts';
import { reduceAll } from '/@fs/home/ellis/.config/vibyra-desktop/terminal-worktrees/vibyra-1a062ef22f2-0/desktop-tauri/src/lib/agentEventReducer.ts';
const noop=async()=>{};
const now=Date.now();
const agents=['Release reviewer','Research assistant'].map((name,i)=>({id:'agent-'+i,account:'audit',name,brief:'Review changes, verify evidence, and prepare a useful report. Ask before publishing.',engine:i?'codex':'claude',model:null,effort:null,permission:i?'plan':'standard',memoryBudget:8000,reflection:'suggest',homePath:'/audit/teammates/'+i,accent:'',mailEnabled:false,routinesAllowed:true,createdMs:now,updatedMs:now,archivedMs:null}));
const chats=[0,1].map(i=>({id:'chat-'+i,account:'audit',agentId:'agent-0',title:i?'Review deployment checklist':'Audit the latest release',engine:'claude',sessionId:null,state:'idle',source:'user',mountedPlace:null,pinned:false,createdMs:now,updatedMs:now,archivedMs:null}));
const approval={id:'approval-0',agentId:'agent-0',agentName:agents[0].name,chatId:'chat-0',turnId:'turn-0',risk:'publish',action:'shell.run',target:'git push origin release-review',detail:'git push origin release-review',costUsd:null,fingerprint:'audit-only',state:'pending',trustable:false,createdMs:now,resolvedMs:null};
const routine={id:'routine-0',agentId:'agent-0',name:'Morning release review',instruction:'Review changes and prepare a report.',schedule:{kind:'daily',minuteOfDay:540},timezone:'Europe/London',permission:'plan',enabled:true,nextRunMs:now+3600000,description:'Daily at 09:00 · Europe/London',createdMs:now,updatedMs:now};
roster.setState({agents,capabilities:['claude','codex'].map(engine=>({engine,installed:true,structured:true,version:engine==='claude'?'2.1.258':'codex-cli 0.150.1',supportsModel:true,supportsEffort:true,supportsImages:engine==='codex',blocker:''})),places:{'agent-0':[{id:'place-0',agentId:'agent-0',path:'/audit/project',access:'readWrite',label:'Release workspace',createdMs:now}]},load:noop,loadPlaces:noop});
const events=[{kind:'turn.started',prompt:'Review this release and prepare a pull request.'},{kind:'tool.requested',callId:'tool-1',tool:'Bash',summary:'git diff --stat'},{kind:'tool.output',callId:'tool-1',tool:'Bash',output:'3 files changed, 42 insertions(+), 8 deletions(-)',exitCode:0,failed:false},{kind:'assistant.completed',text:`I reviewed the changes and prepared the release summary.

- The targeted tests passed.
- The pull request draft is ready to review.

Publishing needs your approval below.`},{kind:'usage.updated',inputTokens:12400,outputTokens:870,costUsd:0.18}].map((e,i)=>({...e,seq:i,chatId:'chat-0',turnId:'turn-0',createdMs:now+i*1000}));
chat.setState({chats:{'agent-0':chats},transcripts:{'chat-0':reduceAll(events),'chat-1':reduceAll([])},loadChats:noop,openChat:noop,adoptRunning:noop});
work.setState({approvals:[approval],approvalChatIds:['chat-0'],routines:[routine],lastCheckedMs:now,loadApprovals:noop,loadRoutines:noop,loadMemory:noop,loadSkills:noop,loadRuns:noop,skills:[],memory:{'agent-0':[]},resolveApproval:async(id)=>work.setState({approvals:[],approvalChatIds:[]})});
attachments.setState({load:noop});
window.audit={mode,roster,work,chat,agents,chats,approval};
window.__TAURI_INTERNALS__={invoke:async()=>[],transformCallback:()=>0};
createRoot(document.getElementById('root')!).render(<div style={{height:'100vh',display:'flex',flexDirection:'column'}}><div style={{height:46,flexShrink:0,borderBottom:'1px solid var(--line)',padding:'10px 18px',color:'var(--muted)'}}>Vibyra · Agent　　<span style={{fontSize:11}}>Audit fixture — current components, synthetic data</span></div><div className="shell" style={{flex:1,minHeight:0}}><AgentMode/></div></div>);
